/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.financeiro;

import Bean.CARBean;
import Bean.CARDocumentosBean;
import DAO.CARDAO;
import DAO.CARDocumentosDAO;
import Methods.Dates;
import Methods.SendEmail;
import Methods.Telas;
import Methods.Valores;
import View.Geral.ProcuraXML;
import View.Geral.ProcurarCliente;
import java.awt.AWTException;
import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.HeadlessException;
import java.io.File;
import java.io.IOException;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.nio.file.Files;
import static java.nio.file.StandardCopyOption.COPY_ATTRIBUTES;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Marcos Filho
 */
public class AdicionarContasAReceber extends javax.swing.JInternalFrame {

    /**
     * Creates new form AdicionarContasPagar
     */
    public AdicionarContasAReceber() {
        initComponents();
    }

    public static void zeracampos() {
        txtcliente.setText("");
        txtnumero.setText("");
        txtemissao.setText("");
        txttotal.setText("");

        DefaultTableModel modelparcela = (DefaultTableModel) tableparcelas.getModel();
        DefaultTableModel modeldocs = (DefaultTableModel) tabledocumentos.getModel();
        DefaultTableModel modelobs = (DefaultTableModel) tableobs.getModel();

        modelparcela.setNumRows(0);
        modeldocs.setNumRows(0);
        modelobs.setNumRows(0);
    }

    public void teladeprocura() {
        ProcuraXML p = new ProcuraXML("CAR");
        Telas.AparecerTela(p);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btnSalvar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtnumero = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtcliente = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtemissao = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        txttotal = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableparcelas = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableobs = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        btnAddDoc = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabledocumentos = new javax.swing.JTable();
        btnprocurar = new javax.swing.JButton();

        setClosable(true);
        setResizable(true);
        setTitle("Adicionar Conta A Receber");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados"));

        jLabel3.setText("Número");

        txtnumero.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel4.setText("Cliente");

        txtcliente.setEditable(false);

        jLabel5.setText("Data de Emissão");

        txtemissao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        txtemissao.setToolTipText("dd/mm/aaaa");

        jLabel6.setText("Valor Total R$");

        txttotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txttotal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txttotalFocusLost(evt);
            }
        });

        jButton6.setText("Procurar Cliente");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtnumero, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtemissao, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(txtemissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txtnumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Contas A Receber"));

        tableparcelas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Parcela", "Vencimento", "Valor R$"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tableparcelas);
        if (tableparcelas.getColumnModel().getColumnCount() > 0) {
            tableparcelas.getColumnModel().getColumn(0).setMinWidth(55);
            tableparcelas.getColumnModel().getColumn(0).setPreferredWidth(55);
            tableparcelas.getColumnModel().getColumn(0).setMaxWidth(55);
        }

        jButton4.setText("Adicionar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton4)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addContainerGap())
        );

        tableobs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Usuário", "Data", "Observação"
            }
        ));
        jScrollPane3.setViewportView(tableobs);
        if (tableobs.getColumnModel().getColumnCount() > 0) {
            tableobs.getColumnModel().getColumn(0).setMinWidth(200);
            tableobs.getColumnModel().getColumn(0).setPreferredWidth(200);
            tableobs.getColumnModel().getColumn(0).setMaxWidth(200);
            tableobs.getColumnModel().getColumn(1).setMinWidth(110);
            tableobs.getColumnModel().getColumn(1).setPreferredWidth(110);
            tableobs.getColumnModel().getColumn(1).setMaxWidth(110);
        }

        jButton5.setText("Incluir Observação");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton5)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Observações", jPanel4);

        btnAddDoc.setText("Adicionar");
        btnAddDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDocActionPerformed(evt);
            }
        });

        jButton3.setText("Excluir");

        tabledocumentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "Descrição", "Local", "Local Original"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabledocumentos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabledocumentosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabledocumentos);
        if (tabledocumentos.getColumnModel().getColumnCount() > 0) {
            tabledocumentos.getColumnModel().getColumn(0).setMinWidth(30);
            tabledocumentos.getColumnModel().getColumn(0).setPreferredWidth(30);
            tabledocumentos.getColumnModel().getColumn(0).setMaxWidth(30);
            tabledocumentos.getColumnModel().getColumn(1).setMinWidth(250);
            tabledocumentos.getColumnModel().getColumn(1).setPreferredWidth(250);
            tabledocumentos.getColumnModel().getColumn(1).setMaxWidth(250);
            tabledocumentos.getColumnModel().getColumn(3).setMinWidth(0);
            tabledocumentos.getColumnModel().getColumn(3).setPreferredWidth(0);
            tabledocumentos.getColumnModel().getColumn(3).setMaxWidth(0);
        }

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddDoc)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddDoc)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Documentos", jPanel6);

        btnprocurar.setText("Procurar XML");
        btnprocurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprocurarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnprocurar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSalvar))
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1))
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnprocurar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        //Total da nota fiscal
        BigDecimal total = new BigDecimal("0");

        //Total das parcelas
        BigDecimal parcelatotal = new BigDecimal("0");
        parcelatotal = parcelatotal.setScale(2, RoundingMode.HALF_EVEN);

        //Verificar se os campos tem valores e então somar para comparar depois
        if (!txttotal.getText().equals("") && tableparcelas.getRowCount() > 0) {
            total = new BigDecimal(Valores.TransformarDinheiroEmValorDouble(txttotal.getText()));
            total = total.setScale(2, RoundingMode.HALF_EVEN);
            
            for (int i = 0; i < tableparcelas.getRowCount(); i++) {
                BigDecimal parcela = new BigDecimal(Valores.TransformarDinheiroEmValorDouble(tableparcelas.getValueAt(i, 2).toString()));
                parcela = parcela.setScale(2, RoundingMode.HALF_EVEN);
                parcelatotal = parcelatotal.add(parcela);
                parcelatotal = parcelatotal.setScale(2, RoundingMode.HALF_EVEN);
            }
        }

        //Verifica se existe fornecedor selecionado, caso não, abre a tela de fornecedor
        if (txtcliente.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Selecione um cliente.");
            ProcurarCliente pf = new ProcurarCliente("CAR");
            JDesktopPane desk = this.getDesktopPane();
            desk.add(pf);
            Dimension jif = pf.getSize();
            Dimension d = desk.getSize();
            pf.setLocation((d.width - jif.width) / 2, (d.height - jif.height) / 2);
            pf.setVisible(true);
        } else if (txtnumero.getText().equals("")) {//Verifica se tem número de nota fiscal
            JOptionPane.showMessageDialog(rootPane, "Coloque o número da nota fiscal por favor.");
            txtnumero.requestFocus();
        } else if (txtemissao.getText().equals("")) {//Verifica se tem data de emissão
            JOptionPane.showMessageDialog(rootPane, "Coloque a data de emissão da nota fiscal por favor.");
            txtemissao.requestFocus();
        } else if (txttotal.getText().equals("")) {//Verifica se tem valor total
            JOptionPane.showMessageDialog(rootPane, "Coloque o valor total da nota fiscal.");
            txttotal.requestFocus();
        } else if (tableparcelas.getRowCount() == 0) {//Verifica se tem parcelas lançadas
            JOptionPane.showMessageDialog(rootPane, "Não existe(m) parcela(s) lançada(s).\nFavor lançar parcela(s).");
        } else if (tabledocumentos.getRowCount() == 0) {//Verifica se tem documento lançado
            JOptionPane.showMessageDialog(rootPane, "Não existe(m) documento(s) lançado(s).\nFavor lançar documento(s).");
        } else if (total.compareTo(parcelatotal) != 0) {//Verifica se os valores das parcelas e do total batem
            if (total.compareTo(parcelatotal) == 1) {
                BigDecimal diff = total.subtract(parcelatotal);
                JOptionPane.showMessageDialog(rootPane, "O(s) valor(es) da(s) parcela(s) não corresponde(m) ao total da nota!\nFalta R$" + diff);
                txttotal.requestFocus();
                txttotal.selectAll();
            } else {
                BigDecimal diff = total.subtract(parcelatotal);
                JOptionPane.showMessageDialog(rootPane, "O(s) valor(es) da(s) parcela(s) não corresponde(m) ao total da nota!\nEstá sobrando R$" + diff);
                txttotal.requestFocus();
                txttotal.selectAll();
            }
        } else {//Caso tudo esteja correto, procede para salvar
            //DAO e Bean para salvar
            CARDAO cd = new CARDAO();
            CARBean cb = new CARBean();

            //DAO e Bean para salvar documento
            CARDocumentosDAO cdd = new CARDocumentosDAO();
            CARDocumentosBean cdb = new CARDocumentosBean();

            //Criar data de lançamento
            String data = Dates.CriarDataCompletaParaDB();

            //Criar CAR
            for (int i = 0; i < tableparcelas.getRowCount(); i++) {
                //Dados para salvar
                cb.setDatalancamento(data);
                cb.setCliente(txtcliente.getText());
                cb.setNotafiscal(Integer.parseInt(txtnumero.getText()));
                cb.setDataemissao(Dates.CriarDataCurtaDBComDataExistente(txtemissao.getText()));
                cb.setTotal(Valores.TransformarDinheiroEmValorDouble(txttotal.getText()));
                cb.setParcela(tableparcelas.getValueAt(i, 0).toString());
                cb.setValorparcela(Valores.TransformarDinheiroEmValorDouble(tableparcelas.getValueAt(i, 2).toString()));
                cb.setDataparcela(Dates.CriarDataCurtaDBComDataExistente(tableparcelas.getValueAt(i, 1).toString()));
                cb.setStatus("Ativo");

                //datalancamento, fornecedor, notafiscal, dataemissao, total, parcela, valorparcela, dataparcela, status
                cd.create(cb);

                //Variável para o ID
                int id = 0;

                //Colocar valor na variável ID
                for (CARBean cb2 : cd.readcreated(data)) {
                    id = cb2.getId();
                }

                //Criar Documentos para o ID
                for (int j = 0; j < tabledocumentos.getRowCount(); j++) {
                    File fileoriginal = new File(tabledocumentos.getValueAt(j, 3).toString());
                    File folder = new File("Q:/MIKE_ERP/car_arq/" + id);
                    File filecopy = new File(folder + "/" + fileoriginal.getName());

                    folder.mkdirs();
                    try {
                        Files.copy(fileoriginal.toPath(), filecopy.toPath(), COPY_ATTRIBUTES);
                    } catch (IOException ex) {
                        Logger.getLogger(AdicionarContasAReceber.class.getName()).log(Level.SEVERE, null, ex);
                        JOptionPane.showMessageDialog(null, "Erro ao salvar!\n" + ex + "\nEnviando e-mail para suporte.");
                        try {
                            SendEmail.EnviarErro(ex.toString());
                            JOptionPane.showMessageDialog(rootPane, "E-mail com erro enviado com sucesso!");
                        } catch (HeadlessException hex) {
                            JOptionPane.showMessageDialog(rootPane, "Erro!\n" + hex);
                        } catch (AWTException | IOException ex1) {
                            Logger.getLogger(AdicionarContasAReceber.class
                                    .getName()).log(Level.SEVERE, null, ex1);
                        }
                    }

                    cdb.setIdcar(id);
                    cdb.setDescricao(tabledocumentos.getValueAt(j, 1).toString());
                    cdb.setLocal(filecopy.toString());

                    //idcar, descricao, local
                    cdd.create(cdb);
                }
            }

            //Mensagem de que foi salvo com sucesso
            JOptionPane.showMessageDialog(rootPane, "Salvo com sucesso!");
            ContasReceber.readtablecar();

            //Pergunta se será lançado outro documento
            int sn = JOptionPane.showConfirmDialog(rootPane, "Deseja lançar outro registro?", "Novo registro", JOptionPane.YES_NO_OPTION);
            if (sn == 0) {
                zeracampos();
                teladeprocura();
            } else {
                dispose();
            }
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void txttotalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txttotalFocusLost
        DecimalFormat formatter = new DecimalFormat("#,###.00");
        String vv = txttotal.getText().replace(".", "");
        String v = formatter.format(Float.parseFloat(vv.replace(",", ".")));
        txttotal.setText(v);
    }//GEN-LAST:event_txttotalFocusLost

    private void btnprocurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprocurarActionPerformed
        teladeprocura();
    }//GEN-LAST:event_btnprocurarActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (txttotal.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Coloque o valor total da nota fiscal primeiro.");
            txttotal.requestFocus();
        } else {
            if (tableparcelas.getRowCount() > 0) {
                int resp = JOptionPane.showConfirmDialog(rootPane, "Já existem parcelas lançadas. Deseja apagar as parcelas lançadas e lançar novas?", "Parcelas já lançadas", JOptionPane.YES_NO_OPTION);
                if (resp == 0) {
                    DefaultTableModel model = (DefaultTableModel) tableparcelas.getModel();
                    model.setNumRows(0);
                    int parcelas = Integer.parseInt(JOptionPane.showInputDialog(null, "Quantas parcelas?", "Adicionar Parcelas", JOptionPane.YES_OPTION));
                    for (int i = 0; i < parcelas; i++) {
                        String valor = txttotal.getText().replace(",", ".");
                        Float parcela = Float.parseFloat(valor) / parcelas;
                        DecimalFormat formatter = new DecimalFormat("#,###.00");
                        String v = formatter.format(parcela);
                        String data = Dates.verificadata1();
                        model.addRow(new Object[]{
                            i + 1 + "/" + String.valueOf(parcelas),
                            data,
                            v
                        });
                    }
                }
            } else {
                DefaultTableModel model = (DefaultTableModel) tableparcelas.getModel();
                model.setNumRows(0);
                int parcelas = Integer.parseInt(JOptionPane.showInputDialog(null, "Quantas parcelas?", "Adicionar Parcelas", JOptionPane.YES_OPTION));
                for (int i = 0; i < parcelas; i++) {
                    String valor = txttotal.getText().replace(".", "");
                    String vv = valor.replace(",", ".");
                    Float parcela = Float.parseFloat(vv) / parcelas;
                    DecimalFormat formatter = new DecimalFormat("#,###.00");
                    String v = formatter.format(parcela);
                    String data = Dates.verificadata1();
                    model.addRow(new Object[]{
                        i + 1 + "/" + String.valueOf(parcelas),
                        data,
                        v
                    });
                }
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnAddDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDocActionPerformed
        DocumentosCAR dcar = new DocumentosCAR();
        JDesktopPane desk = this.getDesktopPane();
        desk.add(dcar);
        Dimension jif = dcar.getSize();
        Dimension d = desk.getSize();
        dcar.setLocation((d.width - jif.width) / 2, (d.height - jif.height) / 2);
        dcar.setVisible(true);
    }//GEN-LAST:event_btnAddDocActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        ProcurarCliente p = new ProcurarCliente("CAR");
        JDesktopPane desk = this.getDesktopPane();
        desk.add(p);
        Dimension jif = p.getSize();
        Dimension d = desk.getSize();
        p.setLocation((d.width - jif.width) / 2, (d.height - jif.height) / 2);
        p.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void tabledocumentosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabledocumentosMouseClicked
        if (evt.getClickCount() == 2) {
            if (!tabledocumentos.getValueAt(tabledocumentos.getSelectedRow(), 3).equals("")) {
                Desktop desk = Desktop.getDesktop();
                try {
                    desk.open(new File((String) tabledocumentos.getValueAt(tabledocumentos.getSelectedRow(), 3)));
                } catch (IOException e) {
                    JOptionPane.showMessageDialog(null, "Erro ao abrir arquivo!\n" + e);
                    try {
                        SendEmail.EnviarErro(e.toString());
                    } catch (AWTException | IOException ex) {
                        Logger.getLogger(AdicionarContasAReceber.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            } else {
                Desktop desk = Desktop.getDesktop();
                try {
                    desk.open(new File((String) tabledocumentos.getValueAt(tabledocumentos.getSelectedRow(), 4)));
                } catch (IOException e) {
                    JOptionPane.showMessageDialog(null, "Erro ao abrir arquivo!\n" + e);
                    try {
                        SendEmail.EnviarErro(e.toString());
                    } catch (AWTException | IOException ex) {
                        Logger.getLogger(AdicionarContasAReceber.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }
    }//GEN-LAST:event_tabledocumentosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAddDoc;
    public static javax.swing.JButton btnSalvar;
    public static javax.swing.JButton btnprocurar;
    public javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.JButton jButton3;
    public javax.swing.JButton jButton4;
    public javax.swing.JButton jButton5;
    public javax.swing.JButton jButton6;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JPanel jPanel3;
    public javax.swing.JPanel jPanel4;
    public javax.swing.JPanel jPanel6;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JTabbedPane jTabbedPane1;
    public static javax.swing.JTable tabledocumentos;
    public static javax.swing.JTable tableobs;
    public static javax.swing.JTable tableparcelas;
    public static javax.swing.JTextField txtcliente;
    public static javax.swing.JFormattedTextField txtemissao;
    public static javax.swing.JTextField txtnumero;
    public static javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables
}
