/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.administracao;

import Bean.GrupoDeUsuariosBean;
import DAO.GrupoDeUsuariosDAO;
import DAO.MenusDAO;
import java.lang.reflect.Field;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Marcos Filho
 */
public class GrupoDeUsuarios extends javax.swing.JInternalFrame {

    /**
     * Creates new form GrupoDeUsuarios
     */
    public GrupoDeUsuarios() {
        initComponents();
        readtablegrupos();
        readtablepermissoes();
    }

    public static void readtablegrupos() {
        DefaultTableModel modelo = (DefaultTableModel) tablegrupos.getModel();
        modelo.setNumRows(0);
        GrupoDeUsuariosDAO gud = new GrupoDeUsuariosDAO();

        gud.read().forEach((c) -> {
            modelo.addRow(new Object[]{
                c.getId(),
                c.getNome()
            });
        });
    }

    public static void readtablepermissoes() {
        DefaultTableModel modelo = (DefaultTableModel) tablepermissoes.getModel();
        modelo.setNumRows(0);
        MenusDAO ud = new MenusDAO();

        ud.read().forEach((c) -> {
            modelo.addRow(new Object[]{
                false,
                c.getNome()
            });
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabgrupos = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablegrupos = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtnomegrupo = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablepermissoes = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtidgrupo = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setTitle("Grupo de Usuários");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tablegrupos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablegrupos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablegruposMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablegrupos);
        if (tablegrupos.getColumnModel().getColumnCount() > 0) {
            tablegrupos.getColumnModel().getColumn(0).setMinWidth(30);
            tablegrupos.getColumnModel().getColumn(0).setPreferredWidth(30);
            tablegrupos.getColumnModel().getColumn(0).setMaxWidth(30);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabgrupos.addTab("Lista de Grupos", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados Grupo"));

        jLabel1.setText("Nome:");

        tablepermissoes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Permissão", "Nome"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablepermissoes.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tablepermissoes);
        if (tablepermissoes.getColumnModel().getColumnCount() > 0) {
            tablepermissoes.getColumnModel().getColumn(0).setMinWidth(100);
            tablepermissoes.getColumnModel().getColumn(0).setPreferredWidth(100);
            tablepermissoes.getColumnModel().getColumn(0).setMaxWidth(100);
            tablepermissoes.getColumnModel().getColumn(1).setResizable(false);
        }

        jLabel2.setText("ID");

        txtidgrupo.setEditable(false);
        txtidgrupo.setBackground(new java.awt.Color(255, 255, 255));

        jButton2.setText("Marcar todos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Desmarcar todos");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtidgrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtnomegrupo))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtnomegrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtidgrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        jButton1.setText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        tabgrupos.addTab("Detalhes Grupo", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabgrupos)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabgrupos)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablegruposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablegruposMouseClicked
        String id = tablegrupos.getValueAt(tablegrupos.getSelectedRow(), 0).toString();
        
        if (evt.getClickCount() == 2) {
            tabgrupos.setSelectedIndex(1);
            txtidgrupo.setText(id);

            GrupoDeUsuariosDAO gud = new GrupoDeUsuariosDAO();
            
            gud.readgrupocadastrado(Integer.parseInt(id)).forEach((ub) -> {
                txtnomegrupo.setText(ub.getNome());
//                for (int i = 0; i < GrupoDeUsuariosBean.getNumberMethodsBoolean(); i++) {
//
//                }
                tablepermissoes.setValueAt(ub.isMenuadministracao(), 0, 0);
                tablepermissoes.setValueAt(ub.isSubmenuusuarios(), 1, 0);
                tablepermissoes.setValueAt(ub.isSubmenugrupodeusuarios(), 2, 0);
                tablepermissoes.setValueAt(ub.isSubmenurepresentantes(), 3, 0);
                tablepermissoes.setValueAt(ub.isSubmenuregioesdeatuacao(), 4, 0);
                tablepermissoes.setValueAt(ub.isMenufiscal(), 5, 0);
                tablepermissoes.setValueAt(ub.isSubmenunotasfiscais(), 6, 0);
                tablepermissoes.setValueAt(ub.isSubmenunaturezadeoperacao(), 7, 0);
                tablepermissoes.setValueAt(ub.isMenucomercial(), 8, 0);
                tablepermissoes.setValueAt(ub.isSubmenuclientes(), 9, 0);
                tablepermissoes.setValueAt(ub.isSubmenugrupodeclientes(), 10, 0);
                tablepermissoes.setValueAt(ub.isSubmenufornecedores(), 11, 0);
                tablepermissoes.setValueAt(ub.isSubmenucategoriadepreco(), 12, 0);
                tablepermissoes.setValueAt(ub.isMenufinanceiro(), 13, 0);
                tablepermissoes.setValueAt(ub.isSubmenucontasareceber(), 14, 0);
                tablepermissoes.setValueAt(ub.isSubmenucontasapagar(), 15, 0);
                tablepermissoes.setValueAt(ub.isSubmenucondicoesdepagamento(), 16, 0);
                tablepermissoes.setValueAt(ub.isSubmenubancos(), 17, 0);
                tablepermissoes.setValueAt(ub.isMenucompras(), 18, 0);
                tablepermissoes.setValueAt(ub.isSubmenusolicitacaodecompras(), 19, 0);
                tablepermissoes.setValueAt(ub.isSubmenuorcamentodecompras(), 20, 0);
                tablepermissoes.setValueAt(ub.isSubmenupedidodecompras(), 21, 0);
                tablepermissoes.setValueAt(ub.isSubmenuinsumos(), 22, 0);
                tablepermissoes.setValueAt(ub.isSubmenutipodeproduto(), 23, 0);
                tablepermissoes.setValueAt(ub.isMenulogistica(), 24, 0);
                tablepermissoes.setValueAt(ub.isSubmenucarros(), 25, 0);
                tablepermissoes.setValueAt(ub.isSubmenurastreamentodedocumentos(), 26, 0);
                tablepermissoes.setValueAt(ub.isMenuqualidade(), 27, 0);
                tablepermissoes.setValueAt(ub.isSubmenuinstrumentosdemedicao(), 28, 0);
                tablepermissoes.setValueAt(ub.isSubmenuiqf(), 29, 0);
                tablepermissoes.setValueAt(ub.isSubmenumedicoes(), 30, 0);
                tablepermissoes.setValueAt(ub.isMenuvendas(), 31, 0);
                tablepermissoes.setValueAt(ub.isSubmenuorcamentosvenda(), 32, 0);
                tablepermissoes.setValueAt(ub.isSubmenupedidosvenda(), 33, 0);
                tablepermissoes.setValueAt(ub.isSubmenuops(), 34, 0);
                tablepermissoes.setValueAt(ub.isSubmenuprodutosvenda(), 35, 0);
                tablepermissoes.setValueAt(ub.isSubmenuprocessosvenda(), 36, 0);
                tablepermissoes.setValueAt(ub.isSubmenugrupodeprocessosvenda(), 37, 0);
                tablepermissoes.setValueAt(ub.isMenuservicos(), 38, 0);
                tablepermissoes.setValueAt(ub.isSubmenuorcamentosservico(), 39, 0);
                tablepermissoes.setValueAt(ub.isSubmenupedidosservico(), 40, 0);
                tablepermissoes.setValueAt(ub.isSubmenuoss(), 41, 0);
                tablepermissoes.setValueAt(ub.isSubmenuprodutosservico(), 42, 0);
                tablepermissoes.setValueAt(ub.isSubmenuprocessosservico(), 43, 0);
                tablepermissoes.setValueAt(ub.isSubmenugrupodeprocessosservico(), 44, 0);
                tablepermissoes.setValueAt(ub.isMenuconfiguracoes(), 45, 0);
                tablepermissoes.setValueAt(ub.isSubmenumenus(), 46, 0);
            });
        }
    }//GEN-LAST:event_tablegruposMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (txtnomegrupo.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Coloque um nome!");
        } else if (txtidgrupo.getText().equals("")) {
            GrupoDeUsuariosBean gub = new GrupoDeUsuariosBean();
            GrupoDeUsuariosDAO gudao = new GrupoDeUsuariosDAO();

            gub.setNome(txtnomegrupo.getText());
            gub.setMenuadministracao(Boolean.valueOf(tablepermissoes.getValueAt(0, 0).toString()));
            gub.setSubmenuusuarios(Boolean.valueOf(tablepermissoes.getValueAt(1, 0).toString()));
            gub.setSubmenugrupodeusuarios(Boolean.valueOf(tablepermissoes.getValueAt(2, 0).toString()));
            gub.setSubmenurepresentantes(Boolean.valueOf(tablepermissoes.getValueAt(3, 0).toString()));
            gub.setSubmenuregioesdeatuacao(Boolean.valueOf(tablepermissoes.getValueAt(4, 0).toString()));
            gub.setMenufiscal(Boolean.valueOf(tablepermissoes.getValueAt(5, 0).toString()));
            gub.setSubmenunotasfiscais(Boolean.valueOf(tablepermissoes.getValueAt(6, 0).toString()));
            gub.setSubmenunaturezadeoperacao(Boolean.valueOf(tablepermissoes.getValueAt(7, 0).toString()));
            gub.setMenucomercial(Boolean.valueOf(tablepermissoes.getValueAt(8, 0).toString()));
            gub.setSubmenuclientes(Boolean.valueOf(tablepermissoes.getValueAt(9, 0).toString()));
            gub.setSubmenugrupodeclientes(Boolean.valueOf(tablepermissoes.getValueAt(10, 0).toString()));
            gub.setSubmenufornecedores(Boolean.valueOf(tablepermissoes.getValueAt(11, 0).toString()));
            gub.setSubmenucategoriadepreco(Boolean.valueOf(tablepermissoes.getValueAt(12, 0).toString()));
            gub.setMenufinanceiro(Boolean.valueOf(tablepermissoes.getValueAt(13, 0).toString()));
            gub.setSubmenucontasareceber(Boolean.valueOf(tablepermissoes.getValueAt(14, 0).toString()));
            gub.setSubmenucontasapagar(Boolean.valueOf(tablepermissoes.getValueAt(15, 0).toString()));
            gub.setSubmenucondicoesdepagamento(Boolean.valueOf(tablepermissoes.getValueAt(16, 0).toString()));
            gub.setSubmenubancos(Boolean.valueOf(tablepermissoes.getValueAt(17, 0).toString()));
            gub.setMenucompras(Boolean.valueOf(tablepermissoes.getValueAt(18, 0).toString()));
            gub.setSubmenusolicitacaodecompras(Boolean.valueOf(tablepermissoes.getValueAt(19, 0).toString()));
            gub.setSubmenuorcamentodecompras(Boolean.valueOf(tablepermissoes.getValueAt(20, 0).toString()));
            gub.setSubmenupedidodecompras(Boolean.valueOf(tablepermissoes.getValueAt(21, 0).toString()));
            gub.setSubmenuinsumos(Boolean.valueOf(tablepermissoes.getValueAt(22, 0).toString()));
            gub.setSubmenutipodeproduto(Boolean.valueOf(tablepermissoes.getValueAt(23, 0).toString()));
            gub.setMenulogistica(Boolean.valueOf(tablepermissoes.getValueAt(24, 0).toString()));
            gub.setSubmenucarros(Boolean.valueOf(tablepermissoes.getValueAt(25, 0).toString()));
            gub.setSubmenurastreamentodedocumentos(Boolean.valueOf(tablepermissoes.getValueAt(26, 0).toString()));
            gub.setMenuqualidade(Boolean.valueOf(tablepermissoes.getValueAt(27, 0).toString()));
            gub.setSubmenuinstrumentosdemedicao(Boolean.valueOf(tablepermissoes.getValueAt(28, 0).toString()));
            gub.setSubmenuiqf(Boolean.valueOf(tablepermissoes.getValueAt(29, 0).toString()));
            gub.setSubmenumedicoes(Boolean.valueOf(tablepermissoes.getValueAt(30, 0).toString()));
            gub.setMenuvendas(Boolean.valueOf(tablepermissoes.getValueAt(31, 0).toString()));
            gub.setSubmenuorcamentosvenda(Boolean.valueOf(tablepermissoes.getValueAt(32, 0).toString()));
            gub.setSubmenupedidosvenda(Boolean.valueOf(tablepermissoes.getValueAt(33, 0).toString()));
            gub.setSubmenuops(Boolean.valueOf(tablepermissoes.getValueAt(34, 0).toString()));
            gub.setSubmenuprodutosvenda(Boolean.valueOf(tablepermissoes.getValueAt(35, 0).toString()));
            gub.setSubmenuprocessosvenda(Boolean.valueOf(tablepermissoes.getValueAt(36, 0).toString()));
            gub.setSubmenugrupodeprocessosvenda(Boolean.valueOf(tablepermissoes.getValueAt(37, 0).toString()));
            gub.setMenuservicos(Boolean.valueOf(tablepermissoes.getValueAt(38, 0).toString()));
            gub.setSubmenuorcamentosservico(Boolean.valueOf(tablepermissoes.getValueAt(39, 0).toString()));
            gub.setSubmenupedidosservico(Boolean.valueOf(tablepermissoes.getValueAt(40, 0).toString()));
            gub.setSubmenuoss(Boolean.valueOf(tablepermissoes.getValueAt(41, 0).toString()));
            gub.setSubmenuprodutosservico(Boolean.valueOf(tablepermissoes.getValueAt(42, 0).toString()));
            gub.setSubmenuprocessosservico(Boolean.valueOf(tablepermissoes.getValueAt(43, 0).toString()));
            gub.setSubmenugrupodeprocessosservico(Boolean.valueOf(tablepermissoes.getValueAt(44, 0).toString()));
            gub.setMenuconfiguracoes(Boolean.valueOf(tablepermissoes.getValueAt(45, 0).toString()));
            gub.setSubmenumenus(Boolean.valueOf(tablepermissoes.getValueAt(46, 0).toString()));

            //nome, menuadministracao, submenuusuarios, submenugrupodeusuarios, submenurepresentantes, submenuregioesdeatuacao, menufiscal, submenunotasfiscais, submenunaturezadeoperacao, menucomercial, submenuclientes, submenugrupodeclientes, submenufornecedores, submenucategoriadepreco, menufinanceiro, submenucontasareceber, submenucontasapagar, submenucondicoesdepagamento, submenubancos, menucompras, submenusolicitacaodecompras, submenuorcamentodecompras, submenupedidodecompras, submenuinsumos, submenutipodeproduto, menulogistica, submenucarros, submenurastreamentodedocumentos, menuqualidade, submenuinstrumentosdemedicao, submenuiqf, submenumedicoes, menuvendas, submenuorcamentosvenda, submenupedidosvenda, submenuops, submenuprodutosvenda, submenuprocessosvenda, submenugrupodeprocessosvenda, menuservicos, submenuorcamentosservico, submenupedidosservico, submenuoss, submenuprodutosservico, submenuprocessosservico, submenugrupodeprocessosservico, menuconfiguracoes, submenumenus
            gudao.create(gub);
            txtidgrupo.setText("");
            txtnomegrupo.setText("");
            tabgrupos.setSelectedIndex(0);
            readtablegrupos();
        } else {
            GrupoDeUsuariosBean gub = new GrupoDeUsuariosBean();
            GrupoDeUsuariosDAO gudao = new GrupoDeUsuariosDAO();

            gub.setNome(txtnomegrupo.getText());
            gub.setMenuadministracao(Boolean.valueOf(tablepermissoes.getValueAt(0, 0).toString()));
            gub.setSubmenuusuarios(Boolean.valueOf(tablepermissoes.getValueAt(1, 0).toString()));
            gub.setSubmenugrupodeusuarios(Boolean.valueOf(tablepermissoes.getValueAt(2, 0).toString()));
            gub.setSubmenurepresentantes(Boolean.valueOf(tablepermissoes.getValueAt(3, 0).toString()));
            gub.setSubmenuregioesdeatuacao(Boolean.valueOf(tablepermissoes.getValueAt(4, 0).toString()));
            gub.setMenufiscal(Boolean.valueOf(tablepermissoes.getValueAt(5, 0).toString()));
            gub.setSubmenunotasfiscais(Boolean.valueOf(tablepermissoes.getValueAt(6, 0).toString()));
            gub.setSubmenunaturezadeoperacao(Boolean.valueOf(tablepermissoes.getValueAt(7, 0).toString()));
            gub.setMenucomercial(Boolean.valueOf(tablepermissoes.getValueAt(8, 0).toString()));
            gub.setSubmenuclientes(Boolean.valueOf(tablepermissoes.getValueAt(9, 0).toString()));
            gub.setSubmenugrupodeclientes(Boolean.valueOf(tablepermissoes.getValueAt(10, 0).toString()));
            gub.setSubmenufornecedores(Boolean.valueOf(tablepermissoes.getValueAt(11, 0).toString()));
            gub.setSubmenucategoriadepreco(Boolean.valueOf(tablepermissoes.getValueAt(12, 0).toString()));
            gub.setMenufinanceiro(Boolean.valueOf(tablepermissoes.getValueAt(13, 0).toString()));
            gub.setSubmenucontasareceber(Boolean.valueOf(tablepermissoes.getValueAt(14, 0).toString()));
            gub.setSubmenucontasapagar(Boolean.valueOf(tablepermissoes.getValueAt(15, 0).toString()));
            gub.setSubmenucondicoesdepagamento(Boolean.valueOf(tablepermissoes.getValueAt(16, 0).toString()));
            gub.setSubmenubancos(Boolean.valueOf(tablepermissoes.getValueAt(17, 0).toString()));
            gub.setMenucompras(Boolean.valueOf(tablepermissoes.getValueAt(18, 0).toString()));
            gub.setSubmenusolicitacaodecompras(Boolean.valueOf(tablepermissoes.getValueAt(19, 0).toString()));
            gub.setSubmenuorcamentodecompras(Boolean.valueOf(tablepermissoes.getValueAt(20, 0).toString()));
            gub.setSubmenupedidodecompras(Boolean.valueOf(tablepermissoes.getValueAt(21, 0).toString()));
            gub.setSubmenuinsumos(Boolean.valueOf(tablepermissoes.getValueAt(22, 0).toString()));
            gub.setSubmenutipodeproduto(Boolean.valueOf(tablepermissoes.getValueAt(23, 0).toString()));
            gub.setMenulogistica(Boolean.valueOf(tablepermissoes.getValueAt(24, 0).toString()));
            gub.setSubmenucarros(Boolean.valueOf(tablepermissoes.getValueAt(25, 0).toString()));
            gub.setSubmenurastreamentodedocumentos(Boolean.valueOf(tablepermissoes.getValueAt(26, 0).toString()));
            gub.setMenuqualidade(Boolean.valueOf(tablepermissoes.getValueAt(27, 0).toString()));
            gub.setSubmenuinstrumentosdemedicao(Boolean.valueOf(tablepermissoes.getValueAt(28, 0).toString()));
            gub.setSubmenuiqf(Boolean.valueOf(tablepermissoes.getValueAt(29, 0).toString()));
            gub.setSubmenumedicoes(Boolean.valueOf(tablepermissoes.getValueAt(30, 0).toString()));
            gub.setMenuvendas(Boolean.valueOf(tablepermissoes.getValueAt(31, 0).toString()));
            gub.setSubmenuorcamentosvenda(Boolean.valueOf(tablepermissoes.getValueAt(32, 0).toString()));
            gub.setSubmenupedidosvenda(Boolean.valueOf(tablepermissoes.getValueAt(33, 0).toString()));
            gub.setSubmenuops(Boolean.valueOf(tablepermissoes.getValueAt(34, 0).toString()));
            gub.setSubmenuprodutosvenda(Boolean.valueOf(tablepermissoes.getValueAt(35, 0).toString()));
            gub.setSubmenuprocessosvenda(Boolean.valueOf(tablepermissoes.getValueAt(36, 0).toString()));
            gub.setSubmenugrupodeprocessosvenda(Boolean.valueOf(tablepermissoes.getValueAt(37, 0).toString()));
            gub.setMenuservicos(Boolean.valueOf(tablepermissoes.getValueAt(38, 0).toString()));
            gub.setSubmenuorcamentosservico(Boolean.valueOf(tablepermissoes.getValueAt(39, 0).toString()));
            gub.setSubmenupedidosservico(Boolean.valueOf(tablepermissoes.getValueAt(40, 0).toString()));
            gub.setSubmenuoss(Boolean.valueOf(tablepermissoes.getValueAt(41, 0).toString()));
            gub.setSubmenuprodutosservico(Boolean.valueOf(tablepermissoes.getValueAt(42, 0).toString()));
            gub.setSubmenuprocessosservico(Boolean.valueOf(tablepermissoes.getValueAt(43, 0).toString()));
            gub.setSubmenugrupodeprocessosservico(Boolean.valueOf(tablepermissoes.getValueAt(44, 0).toString()));
            gub.setMenuconfiguracoes(Boolean.valueOf(tablepermissoes.getValueAt(45, 0).toString()));
            gub.setSubmenumenus(Boolean.valueOf(tablepermissoes.getValueAt(46, 0).toString()));
            gub.setId(Integer.parseInt(txtidgrupo.getText()));

            //nome = ?, menuadministracao = ?, submenuusuarios = ?, submenugrupodeusuarios = ?, submenurepresentantes = ?, submenuregioesdeatuacao = ?, menufiscal = ?, submenunotasfiscais = ?, submenunaturezadeoperacao = ?, menucomercial = ?, submenuclientes = ?, submenugrupodeclientes = ?, submenufornecedores = ?, submenucategoriadepreco = ?, menufinanceiro = ?, submenucontasareceber = ?, submenucontasapagar = ?, submenucondicoesdepagamento = ?, submenubancos = ?, menucompras = ?, submenusolicitacaodecompras = ?, submenuorcamentodecompras = ?, submenupedidodecompras = ?, submenuinsumos = ?, submenutipodeproduto = ?, menulogistica = ?, submenucarros = ?, submenurastreamentodedocumentos = ?, menuqualidade = ?, submenuinstrumentosdemedicao = ?, submenuiqf = ?, submenumedicoes = ?, menuvendas = ?, submenuorcamentosvenda = ?, submenupedidosvenda = ?, submenuops = ?, submenuprodutosvenda = ?, submenuprocessosvenda = ?, submenugrupodeprocessosvenda = ?, menuservicos = ?, submenuorcamentosservico = ?, submenupedidosservico = ?, submenuoss = ?, submenuprodutosservico = ?, submenuprocessosservico = ?, submenugrupodeprocessosservico = ?, menuconfiguracoes = ?, submenumenus = ? WHERE id = ?
            gudao.update(gub);
            txtidgrupo.setText("");
            txtnomegrupo.setText("");
            tabgrupos.setSelectedIndex(0);
            readtablegrupos();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int i = tablepermissoes.getRowCount();
        for (int j = 0; j < i; j++) {
            tablepermissoes.setValueAt(false, j, 0);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int i = tablepermissoes.getRowCount();
        for (int j = 0; j < i; j++) {
            tablepermissoes.setValueAt(true, j, 0);
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton1;
    public javax.swing.JButton jButton2;
    public javax.swing.JButton jButton3;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JPanel jPanel3;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTabbedPane tabgrupos;
    public static javax.swing.JTable tablegrupos;
    public static javax.swing.JTable tablepermissoes;
    public static javax.swing.JTextField txtidgrupo;
    public static javax.swing.JTextField txtnomegrupo;
    // End of variables declaration//GEN-END:variables
}
