/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.administracao;

import DAO.GrupoDeUsuariosDAO;
import DAO.GrupoDeUsuariosPermDAO;
import View.TelaPrincipal;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Marcos Filho
 */
public class GrupoDeUsuarios extends javax.swing.JInternalFrame {

    /**
     * Creates new form GrupoDeUsuarios
     */
    private int id = 0;

    GrupoDeUsuariosDAO gd = new GrupoDeUsuariosDAO();
    GrupoDeUsuariosPermDAO gupd = new GrupoDeUsuariosPermDAO();

    public GrupoDeUsuarios() {
        initComponents();
        readtablegrupos();
        readtablepermissoes();
    }

    public static void readtablegrupos() {
        DefaultTableModel modelo = (DefaultTableModel) tablegrupos.getModel();
        modelo.setNumRows(0);
        GrupoDeUsuariosDAO gud = new GrupoDeUsuariosDAO();

        gud.read().forEach((c) -> {
            modelo.addRow(new Object[]{
                c.getId(),
                c.getNome()
            });
        });
    }

    public static void readtablepermissoes() {
        DefaultTableModel modelo = (DefaultTableModel) tablepermissoes.getModel();
        modelo.setNumRows(0);

        int menu = TelaPrincipal.jMenuBar1.getMenuCount();
        for (int i = 0; i < menu; i++) {
            String menuname = TelaPrincipal.jMenuBar1.getMenu(i).getName();
            modelo.addRow(new Object[]{
                "",
                false,
                menuname
            });
            int sub = TelaPrincipal.jMenuBar1.getMenu(i).getItemCount();
            for (int j = 0; j < sub; j++) {
                String subname = TelaPrincipal.jMenuBar1.getMenu(i).getItem(j).getName();
                modelo.addRow(new Object[]{
                    "",
                    false,
                    subname
                });
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabgrupos = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablegrupos = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtnomegrupo = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablepermissoes = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setTitle("Grupo de Usuários");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tablegrupos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablegrupos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablegruposMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablegrupos);
        if (tablegrupos.getColumnModel().getColumnCount() > 0) {
            tablegrupos.getColumnModel().getColumn(0).setMinWidth(30);
            tablegrupos.getColumnModel().getColumn(0).setPreferredWidth(30);
            tablegrupos.getColumnModel().getColumn(0).setMaxWidth(30);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabgrupos.addTab("Lista de Grupos", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados Grupo"));

        jLabel1.setText("Nome:");

        tablepermissoes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Permissão", "Nome"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Boolean.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablepermissoes.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tablepermissoes);
        if (tablepermissoes.getColumnModel().getColumnCount() > 0) {
            tablepermissoes.getColumnModel().getColumn(0).setMinWidth(40);
            tablepermissoes.getColumnModel().getColumn(0).setPreferredWidth(40);
            tablepermissoes.getColumnModel().getColumn(0).setMaxWidth(40);
            tablepermissoes.getColumnModel().getColumn(1).setMinWidth(75);
            tablepermissoes.getColumnModel().getColumn(1).setPreferredWidth(75);
            tablepermissoes.getColumnModel().getColumn(1).setMaxWidth(75);
            tablepermissoes.getColumnModel().getColumn(2).setResizable(false);
        }

        jButton2.setText("Marcar todos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Desmarcar todos");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtnomegrupo))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtnomegrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        jButton1.setText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        tabgrupos.addTab("Detalhes Grupo", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabgrupos)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabgrupos)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablegruposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablegruposMouseClicked
        id = Integer.parseInt(tablegrupos.getValueAt(tablegrupos.getSelectedRow(), 0).toString());

        if (evt.getClickCount() == 2) {
            tabgrupos.setSelectedIndex(1);

            gd.readgrupocadastrado(id).forEach((ub) -> {
                txtnomegrupo.setText(ub.getNome());
            });

            for (int i = 0; i < tablepermissoes.getRowCount(); i++) {
                if (tablepermissoes.getValueAt(i, 2) != null) {
                    boolean perm = gupd.readPerm(id, tablepermissoes.getValueAt(i, 2).toString());
                    tablepermissoes.setValueAt(perm, i, 1);
                    String id2 = String.valueOf(gupd.readId(id, tablepermissoes.getValueAt(i, 2).toString()));
                    tablepermissoes.setValueAt(id2, i, 0);
                }
            }
        }
    }//GEN-LAST:event_tablegruposMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (txtnomegrupo.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Coloque um nome!");
        } else if (id == 0) {
            gd.create2(txtnomegrupo.getText());

            int idgrupo = gd.created(txtnomegrupo.getText());

            for (int i = 0; i < tablepermissoes.getRowCount(); i++) {
                gupd.create(idgrupo, tablepermissoes.getValueAt(i, 1).toString(), Boolean.parseBoolean(tablepermissoes.getValueAt(i, 0).toString()));
            }
        } else {
            gd.update2(txtnomegrupo.getText(), id);

            for (int i = 0; i < tablepermissoes.getRowCount(); i++) {
                if (tablepermissoes.getValueAt(i, 0).equals("0")) {
                    gupd.create(id, tablepermissoes.getValueAt(i, 2).toString(), Boolean.parseBoolean(tablepermissoes.getValueAt(i, 1).toString()));
                } else {
                    int idpermissao = Integer.parseInt(tablepermissoes.getValueAt(i, 0).toString());
                    gupd.update(idpermissao, Boolean.parseBoolean(tablepermissoes.getValueAt(i, 1).toString()));
                }
            }
        }
        txtnomegrupo.setText("");
        tabgrupos.setSelectedIndex(0);
        readtablepermissoes();
        readtablegrupos();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int i = tablepermissoes.getRowCount();
        for (int j = 0; j < i; j++) {
            tablepermissoes.setValueAt(false, j, 1);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int i = tablepermissoes.getRowCount();
        for (int j = 0; j < i; j++) {
            tablepermissoes.setValueAt(true, j, 1);
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton1;
    public javax.swing.JButton jButton2;
    public javax.swing.JButton jButton3;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JPanel jPanel3;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTabbedPane tabgrupos;
    public static javax.swing.JTable tablegrupos;
    public static javax.swing.JTable tablepermissoes;
    public static javax.swing.JTextField txtnomegrupo;
    // End of variables declaration//GEN-END:variables
}
