/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Geral;

import Methods.Obs;
import Methods.SendEmail;
import View.compras.ComprasSolicitacao;
import View.compras.ComprasCotacao;
import View.compras.Insumos;
import View.compras.TiposInsumo;
import View.financeiro.AdicionarContasAPagar;
import View.financeiro.AdicionarContasAReceber;
import View.financeiro.ContaPagar;
import View.financeiro.ContaReceber;
import View.vendas.CotacaoVenda;
import View.vendas.OP;
import View.vendas.PedidoVenda;
import View.vendas.VM1;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author Marcos Filho
 */
public class AdicionarObs extends javax.swing.JInternalFrame {

    String origem;
    JTable table;

    /**
     * Creates new form AdicionarObs
     *
     * @param origin
     */
    public AdicionarObs(String origin) {
        initComponents();
        this.origem = origin;
    }

    public void adicionar() {
        if (txtobs.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Favor digitar uma observação.");
            txtobs.requestFocus();
        } else {
            String obs = txtobs.getText();
            switch (origem) {
                case "TiposInsumo":
                    Obs.AdicionarObs(TiposInsumo.tableobs, obs);
                    break;
                case "Insumos":
                    Obs.AdicionarObs(Insumos.tableobs, obs);
                    break;
                case "ContaPagar":
                    Obs.AdicionarObs(ContaPagar.tableobs, obs);
                    break;
                case "CotacaoVenda":
                    Obs.AdicionarObs(CotacaoVenda.tableObs, obs);
                    break;
                case "PedidoVenda":
                    Obs.AdicionarObs(PedidoVenda.tableObs, obs);
                    break;
                case "OP":
                    Obs.AdicionarObs(OP.tableObs, obs);
                    if (!OP.txtNumOP.getText().equals("")) {
                        try {
                            OP.salvarObs(OP.txtNumOP.getText());
                            OP.lerObs(OP.txtNumOP.getText());
                        } catch (SQLException e) {
                            String msg = "Erro.";

                            JOptionPane.showMessageDialog(null, msg + "\n" + e);

                            new Thread() {
                                @Override
                                public void run() {
                                    SendEmail.EnviarErro2(msg, e);
                                }
                            }.start();
                        }
                    }
                    break;
                case "ComprasSolicitacao":
                    Obs.AdicionarObs(ComprasSolicitacao.tableobs, obs);
                    break;
                case "CotacaoCompras":
                    Obs.AdicionarObs(ComprasCotacao.tableObs, obs);
                    break;
                case "AdicionarContasAReceber":
                    Obs.AdicionarObs(AdicionarContasAReceber.tableobs, obs);
                    break;
                case "ContaReceber":
                    Obs.AdicionarObs(ContaReceber.tableObs, obs);
                    break;
                case "VM1":
                    Obs.AdicionarObs(VM1.tableobs, obs);
                    break;
                case "AdicionarContasAPagar":
                    Obs.AdicionarObs(AdicionarContasAPagar.tableobs, obs);
                    break;
            }
            dispose();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtobs = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setTitle("Adicionar Observação");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setName("jPanel1"); // NOI18N

        jLabel1.setText("Observação");
        jLabel1.setName("jLabel1"); // NOI18N

        txtobs.setName("txtobs"); // NOI18N
        txtobs.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtobsKeyReleased(evt);
            }
        });

        jButton1.setText("Adicionar");
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtobs, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtobs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        adicionar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtobsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtobsKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            adicionar();
        }
    }//GEN-LAST:event_txtobsKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton1;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JTextField txtobs;
    // End of variables declaration//GEN-END:variables
}
