/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Geral;

import Bean.AltBean;
import View.comercial.*;
import DAO.AltDAO;
import Methods.Dates;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Marcos Filho
 */
public class HistoricoAlteracao extends javax.swing.JInternalFrame {

    /**
     * Creates new form HistoricoAlteracao
     */
    static String origem;

    public HistoricoAlteracao(String origin) {
        initComponents();
        origem = origin;
        read();
    }

    public static void read() {
        //Zerar número de linhas da table
        DefaultTableModel model = (DefaultTableModel) tablehist.getModel();
        model.setNumRows(0);
        
        //Verificar origem e mostrar resultado correto.
        switch (origem) {
            case "Fornecedor":
                //DAO para consulta
                AltDAO ad = new AltDAO();

                for (AltBean ab : ad.read(Integer.parseInt(Fornecedores.txtidfornecedor.getText()),"fornecedores_alt","idfornecedor")) {
                    String datadb = ab.getData();

                    model.addRow(new Object[]{
                        Dates.TransformarDataCompletaDoDB(datadb),
                        ab.getUser(),
                        ab.getValor(),
                        ab.getValoranterior(),
                        ab.getValornovo()
                    });
                }
                break;
            case "HistDoc":
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablehist = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setTitle("Histórico de Alterações");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tablehist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Data", "Usuário", "Valor", "Valor Anterior", "Valor Novo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablehist);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1026, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable tablehist;
    // End of variables declaration//GEN-END:variables
}
