/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Geral;

import DAO.ServicoMateriaisDAO;
import DAO.VendasMateriaisDAO;
import View.comercial.CategoriaDePreco;
import View.servicos.OS;
import View.vendas.VM;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Marcos Filho
 */
public class ProcuraMaterial extends javax.swing.JInternalFrame {

    /**
     * Creates new form ProcuraMaterialVenda
     */
    private static String origem;

    static ServicoMateriaisDAO smd = new ServicoMateriaisDAO();
    static VendasMateriaisDAO vmd = new VendasMateriaisDAO();

    public ProcuraMaterial(String origin) {
        initComponents();
        origem = origin;
        readtablemateriais();
    }

    public static void readtablemateriais() {
        DefaultTableModel model = (DefaultTableModel) tablemateriais.getModel();
        model.setNumRows(0);

        switch (origem) {
            case "VendasMaterial":
                vmd.readStatus("Ativo").forEach(vmb -> {
                    model.addRow(new Object[]{
                        vmb.getId(),
                        vmb.getCodigo(),
                        vmb.getDescricao()
                    });
                });
                break;
            case "VM":
                vmd.readStatus("Ativo").forEach(vmb -> {
                    model.addRow(new Object[]{
                        vmb.getId(),
                        vmb.getCodigo(),
                        vmb.getDescricao()
                    });
                });
                break;
            case "OS":
                smd.read().forEach(smb -> {
                    model.addRow(new Object[]{
                        smb.getId(),
                        smb.getCodigo(),
                        smb.getDescricao()
                    });
                });
                break;
            case "CategoriaDePreco":
                smd.read().forEach(smb -> {
                    model.addRow(new Object[]{
                        smb.getId(),
                        smb.getCodigo(),
                        smb.getDescricao()
                    });
                });
                break;
            case "CotacaoVenda":
                vmd.readStatus("Ativo").forEach(vmb -> {
                    model.addRow(new Object[]{
                        vmb.getId(),
                        vmb.getCodigo(),
                        vmb.getDescricao()
                    });
                });
                break;
            case "CotacaoServico":
                smd.read().forEach(smb -> {
                    model.addRow(new Object[]{
                        smb.getId(),
                        smb.getCodigo(),
                        smb.getDescricao()
                    });
                });
                break;
            case "PedidoVenda":
                vmd.readStatus("Ativo").forEach(vmb -> {
                    model.addRow(new Object[]{
                        vmb.getId(),
                        vmb.getCodigo(),
                        vmb.getDescricao()
                    });
                });
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablemateriais = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        txtpesquisa = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setTitle("Procurar Material");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setName("jPanel1"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        tablemateriais.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Código", "Descrição"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablemateriais.setName("tablemateriais"); // NOI18N
        tablemateriais.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablemateriaisMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablemateriais);
        if (tablemateriais.getColumnModel().getColumnCount() > 0) {
            tablemateriais.getColumnModel().getColumn(0).setMinWidth(0);
            tablemateriais.getColumnModel().getColumn(0).setPreferredWidth(0);
            tablemateriais.getColumnModel().getColumn(0).setMaxWidth(0);
            tablemateriais.getColumnModel().getColumn(1).setMinWidth(150);
            tablemateriais.getColumnModel().getColumn(1).setPreferredWidth(150);
            tablemateriais.getColumnModel().getColumn(1).setMaxWidth(150);
        }

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesquisa"));
        jPanel2.setName("jPanel2"); // NOI18N

        txtpesquisa.setName("txtpesquisa"); // NOI18N
        txtpesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtpesquisaKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtpesquisa)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtpesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablemateriaisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablemateriaisMouseClicked
        if (evt.getClickCount() == 2) {
            String codigo = tablemateriais.getValueAt(tablemateriais.getSelectedRow(), 1).toString();
            String desc = tablemateriais.getValueAt(tablemateriais.getSelectedRow(), 2).toString();
            switch (origem) {
                case "VM":
                    VM.txtmaterialdeorigem.setText(codigo);
                    break;
                case "OS":
                    OS.txtcodigo.setText(codigo);
                    OS.txtdesc.setText(desc);
                    break;
                case "CategoriaDePreco":
                    DefaultTableModel model = (DefaultTableModel) CategoriaDePreco.tableferramentas.getModel();
                    model.addRow(new Object[]{
                        "",
                        codigo,
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",});
                    break;
                case "CotacaoVenda":
                    ItemCotacao.txtcodigo.setText(codigo);
                    ItemCotacao.txtdesc.setText(desc);
                    break;
                case "CotacaoServico":
                    ItemCotacao.txtcodigo.setText(codigo);
                    ItemCotacao.txtdesc.setText(desc);
                    break;
                case "PedidoVenda":
                    ItemPedido.txtcodigo.setText(codigo);
                    ItemPedido.txtdesc.setText(desc);
                    break;
            }
            dispose();
        }
    }//GEN-LAST:event_tablemateriaisMouseClicked

    private void txtpesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpesquisaKeyReleased
        DefaultTableModel model = (DefaultTableModel) tablemateriais.getModel();
        model.setNumRows(0);
        
        switch (origem) {
            case "CotacaoServico":
                smd.pesquisa(txtpesquisa.getText()).forEach(smb -> {
                    model.addRow(new Object[]{
                        smb.getId(),
                        smb.getCodigo(),
                        smb.getDescricao()
                    });
                });
                break;
            case "CotacaoVenda":
                vmd.readTodosPesquisa(txtpesquisa.getText()).forEach(vmb -> {
                    model.addRow(new Object[]{
                        vmb.getId(),
                        vmb.getCodigo(),
                        vmb.getDescricao()
                    });
                });
                break;
            case "PedidoVenda":
                vmd.readTodosPesquisa(txtpesquisa.getText()).forEach(vmb -> {
                    model.addRow(new Object[]{
                        vmb.getId(),
                        vmb.getCodigo(),
                        vmb.getDescricao()
                    });
                });
                break;
        }
    }//GEN-LAST:event_txtpesquisaKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable tablemateriais;
    public javax.swing.JTextField txtpesquisa;
    // End of variables declaration//GEN-END:variables
}
