/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Geral;

import DAO.ServicoPedidoDAO;
import DAO.ServicoPedidoItensDAO;
import DAO.VendasPedidoDAO;
import DAO.VendasPedidoItensDAO;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Marcos Filho
 */
public class ProcurarPedido extends javax.swing.JInternalFrame {

    static VendasPedidoDAO vpd = new VendasPedidoDAO();
    static ServicoPedidoDAO spd = new ServicoPedidoDAO();
    static VendasPedidoItensDAO vpid = new VendasPedidoItensDAO();
    static ServicoPedidoItensDAO spid = new ServicoPedidoItensDAO();

    static String origem, codigo;

    /**
     * Creates new form ProcurarPedido
     *
     * @param origin
     * @param cliente
     * @param code
     */
    public ProcurarPedido(String origin, String cliente, String code) {
        initComponents();
        origem = origin;
        codigo = code;
        lerPedidos(origin, cliente);
    }

    public static void lerPedidos(String o, String c) {
        DefaultTableModel modelPedido = (DefaultTableModel) tablePedidos.getModel();
        modelPedido.setNumRows(0);

        switch (o) {
            case "OP":
                vpd.readPedidosAbertosPorCliente(c).forEach(vpb -> {
                    modelPedido.addRow(new Object[]{
                        vpb.getId(),
                        vpb.getPedido(),
                        vpb.getCliente()
                    });
                });
                break;
            case "OS":

                break;
        }
    }

    public static void lerItens(String pedido, String origem) {
        DefaultTableModel modelItens = (DefaultTableModel) tableItensPedido.getModel();
        modelItens.setNumRows(0);

        switch (origem) {
            case "OP":
                vpid.readItensSemOp(pedido, codigo).forEach(vpib -> {
                    modelItens.addRow(new Object[]{
                        vpib.getId(),
                        vpib.getCodigo(),
                        vpib.getDescricao()
                    });
                });
                break;
            case "OS":

                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePedidos = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableItensPedido = new javax.swing.JTable();

        setClosable(true);
        setTitle("Procurar Pedido");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setName("jPanel1"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        tablePedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Pedido", "Cliente"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablePedidos.setName("tablePedidos"); // NOI18N
        tablePedidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePedidosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablePedidos);
        if (tablePedidos.getColumnModel().getColumnCount() > 0) {
            tablePedidos.getColumnModel().getColumn(0).setMinWidth(0);
            tablePedidos.getColumnModel().getColumn(0).setPreferredWidth(0);
            tablePedidos.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        tableItensPedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Código", "Descrição"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableItensPedido.setName("tableItensPedido"); // NOI18N
        jScrollPane2.setViewportView(tableItensPedido);
        if (tableItensPedido.getColumnModel().getColumnCount() > 0) {
            tableItensPedido.getColumnModel().getColumn(0).setMinWidth(0);
            tableItensPedido.getColumnModel().getColumn(0).setPreferredWidth(0);
            tableItensPedido.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablePedidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePedidosMouseClicked
        lerItens(tablePedidos.getValueAt(tablePedidos.getSelectedRow(), 1).toString(), origem);
    }//GEN-LAST:event_tablePedidosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel jPanel1;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTable tableItensPedido;
    public static javax.swing.JTable tablePedidos;
    // End of variables declaration//GEN-END:variables
}
