/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.vendas;

import DAO.RevestimentoDAO;
import Methods.Telas;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Marcos Filho
 */
public class CadastroDeRevestimento extends javax.swing.JInternalFrame {

    static RevestimentoDAO rd = new RevestimentoDAO();

    /**
     * Creates new form CadastroDeRevestimento
     */
    public CadastroDeRevestimento() {
        initComponents();
        lerRevestimentos();
    }

    public static void lerRevestimentos() {
        DefaultTableModel model = (DefaultTableModel) tableRev.getModel();
        model.setNumRows(0);

        rd.readTodos().forEach(rb -> {
            model.addRow(new Object[]{
                rb.getId(),
                false,
                rb.getNome(),
                rb.getCodigo()
            });
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableRev = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setClosable(true);
        setTitle("Cadastro de Revestimento");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setName("jPanel1"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        tableRev.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "", "Nome", "Código"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableRev.setName("tableRev"); // NOI18N
        tableRev.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableRevMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableRev);
        if (tableRev.getColumnModel().getColumnCount() > 0) {
            tableRev.getColumnModel().getColumn(0).setMinWidth(0);
            tableRev.getColumnModel().getColumn(0).setPreferredWidth(0);
            tableRev.getColumnModel().getColumn(0).setMaxWidth(0);
            tableRev.getColumnModel().getColumn(1).setMinWidth(35);
            tableRev.getColumnModel().getColumn(1).setPreferredWidth(35);
            tableRev.getColumnModel().getColumn(1).setMaxWidth(35);
        }

        jButton1.setText("Adicionar");
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Excluir");
        jButton2.setName("jButton2"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        NovoRevestimento nr = new NovoRevestimento();
        Telas.AparecerTela(nr);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tableRevMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableRevMouseClicked
        if (evt.getClickCount() == 2) {
            NovoRevestimento nr = new NovoRevestimento();
            NovoRevestimento.idRev = Integer.parseInt(tableRev.getValueAt(tableRev.getSelectedRow(), 0).toString());
            Telas.AparecerTela(nr);
        }
    }//GEN-LAST:event_tableRevMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int numTrue = 0;

        for (int i = 0; i < tableRev.getRowCount(); i++) {
            if (tableRev.getValueAt(i, 1).equals(true)) {
                numTrue++;
            }
        }

        if (numTrue == 0) {
            JOptionPane.showMessageDialog(null, "Nenhum registro selecionado.");
        } else {
            int resp = JOptionPane.showConfirmDialog(null, "Deseja excluir os revestimentos selecionados?", "Excluir Revestimentos", JOptionPane.YES_NO_OPTION);

            if (resp == 0) {
                for (int i = 0; i < tableRev.getRowCount(); i++) {
                    if (tableRev.getValueAt(i, 1).equals(true)) {
                        int id = Integer.parseInt(tableRev.getValueAt(i, 0).toString());
                        rd.delete(id);
                    }
                }

                lerRevestimentos();
                VM1.lerRevestimento();
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton1;
    public javax.swing.JButton jButton2;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable tableRev;
    // End of variables declaration//GEN-END:variables
}
