/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.vendas;

import DAO.FerramentasDAO;
import DAO.FerramentasFamiliaDAO;
import DAO.FerramentasTamanhoDAO;
import Methods.SendEmail;
import Methods.Telas;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Marcos Filho
 */
public class CadastroDeFerramenta extends javax.swing.JInternalFrame {

    FerramentasDAO fd = new FerramentasDAO();
    static FerramentasFamiliaDAO ffd = new FerramentasFamiliaDAO();
    FerramentasTamanhoDAO ftd = new FerramentasTamanhoDAO();

    int idFerramenta = 0;

    /**
     * Creates new form CadastroDeFerramenta
     */
    public CadastroDeFerramenta() {
        initComponents();
        lerFerramentas();
    }

    public void lerFerramentas() {
        DefaultTableModel model = (DefaultTableModel) tableFerramentas.getModel();
        model.setNumRows(0);

        fd.readTodos().forEach(fb -> {
            model.addRow(new Object[]{
                fb.getId(),
                false,
                fb.getNome(),
                fb.getDescricao()
            });
        });
    }

    private void lerFerramenta(String nomeFerramenta) {
        fd.readFerramenta(nomeFerramenta).forEach(fb -> {
            txtNome.setText(fb.getNome());
            txtDescricao.setText(fb.getDescricao());
        });

        lerFamilias(nomeFerramenta);

        lerTamanhos(nomeFerramenta);
    }

    public static void lerFamilias(String nomeFerramenta) {
        DefaultTableModel model = (DefaultTableModel) tableFamilias.getModel();
        model.setNumRows(0);

        ffd.read(nomeFerramenta).forEach(ffb -> {
            model.addRow(new Object[]{
                ffb.getId(),
                false,
                ffb.getNome(),
                ffb.getCodigo(),
                ffb.getDescricao()
            });
        });
    }

    private void lerTamanhos(String nomeFerramenta) {
        DefaultTableModel model = (DefaultTableModel) tableTamanhos.getModel();
        model.setNumRows(0);

        ftd.read(nomeFerramenta).forEach(ftb -> {
            model.addRow(new Object[]{
                ftb.getId(),
                false,
                ftb.getCodigo()
            });
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabFerramentas = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableFerramentas = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtNome = new javax.swing.JTextField();
        txtDescricao = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableFamilias = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableTamanhos = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setClosable(true);
        setTitle("Cadastro de Ferramentas");

        tabFerramentas.setName("tabFerramentas"); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setName("jPanel1"); // NOI18N

        jScrollPane3.setName("jScrollPane3"); // NOI18N

        tableFerramentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "", "Nome", "Descrição"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableFerramentas.setName("tableFerramentas"); // NOI18N
        tableFerramentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableFerramentasMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tableFerramentas);
        if (tableFerramentas.getColumnModel().getColumnCount() > 0) {
            tableFerramentas.getColumnModel().getColumn(0).setMinWidth(0);
            tableFerramentas.getColumnModel().getColumn(0).setPreferredWidth(0);
            tableFerramentas.getColumnModel().getColumn(0).setMaxWidth(0);
            tableFerramentas.getColumnModel().getColumn(1).setMinWidth(35);
            tableFerramentas.getColumnModel().getColumn(1).setPreferredWidth(35);
            tableFerramentas.getColumnModel().getColumn(1).setMaxWidth(35);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        tabFerramentas.addTab("Cadastros", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setName("jPanel2"); // NOI18N

        jLabel1.setText("Nome");
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setText("Descrição da Ferramenta");
        jLabel2.setName("jLabel2"); // NOI18N

        jButton1.setText("Salvar");
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtNome.setName("txtNome"); // NOI18N

        txtDescricao.setName("txtDescricao"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        tableFamilias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "", "Nome", "Código", "Descrição"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableFamilias.setName("tableFamilias"); // NOI18N
        tableFamilias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableFamiliasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableFamilias);
        if (tableFamilias.getColumnModel().getColumnCount() > 0) {
            tableFamilias.getColumnModel().getColumn(0).setMinWidth(0);
            tableFamilias.getColumnModel().getColumn(0).setPreferredWidth(0);
            tableFamilias.getColumnModel().getColumn(0).setMaxWidth(0);
            tableFamilias.getColumnModel().getColumn(1).setMinWidth(35);
            tableFamilias.getColumnModel().getColumn(1).setPreferredWidth(35);
            tableFamilias.getColumnModel().getColumn(1).setMaxWidth(35);
        }

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        tableTamanhos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "", "Código"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Boolean.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableTamanhos.setName("tableTamanhos"); // NOI18N
        jScrollPane2.setViewportView(tableTamanhos);
        if (tableTamanhos.getColumnModel().getColumnCount() > 0) {
            tableTamanhos.getColumnModel().getColumn(0).setMinWidth(0);
            tableTamanhos.getColumnModel().getColumn(0).setPreferredWidth(0);
            tableTamanhos.getColumnModel().getColumn(0).setMaxWidth(0);
            tableTamanhos.getColumnModel().getColumn(1).setMinWidth(35);
            tableTamanhos.getColumnModel().getColumn(1).setPreferredWidth(35);
            tableTamanhos.getColumnModel().getColumn(1).setMaxWidth(35);
        }

        jButton2.setText("Adicionar Tamanho");
        jButton2.setName("jButton2"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Adicionar Família");
        jButton3.setName("jButton3"); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Deletar Família");
        jButton4.setName("jButton4"); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jButton4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton3)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(152, 152, 152))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        tabFerramentas.addTab("Detalhes", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabFerramentas)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabFerramentas, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (txtNome.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Digite um nome primeiro.");
            txtNome.requestFocus();
        } else {
            String nomeFerramenta = txtNome.getText();

            if (idFerramenta == 0) {
                try {
                    fd.create(nomeFerramenta, txtDescricao.getText());

                    for (int i = 0; i < tableFamilias.getRowCount(); i++) {
                        ffd.create(nomeFerramenta, tableFamilias.getValueAt(i, 2).toString(), tableFamilias.getValueAt(i, 3).toString(), tableFamilias.getValueAt(i, 4).toString());
                    }

                    for (int i = 0; i < tableTamanhos.getRowCount(); i++) {
                        ftd.create(nomeFerramenta, tableTamanhos.getValueAt(i, 2).toString());
                    }

                    JOptionPane.showMessageDialog(null, "Criado com sucesso.");
                } catch (SQLException e) {
                    String msg = "Erro ao criar Ferramenta.";
                    JOptionPane.showMessageDialog(null, msg + "\n" + e);

                    new Thread() {
                        @Override
                        public void run() {
                            SendEmail.EnviarErro2(msg, e);
                        }
                    }.start();
                }
            } else {
                try {
                    fd.update(nomeFerramenta, txtDescricao.getText(), idFerramenta);

                    for (int i = 0; i < tableFamilias.getRowCount(); i++) {
                        if (tableFamilias.getValueAt(i, 0).equals("")) {
                            ffd.create(nomeFerramenta, tableFamilias.getValueAt(i, 2).toString(), tableFamilias.getValueAt(i, 3).toString(), tableFamilias.getValueAt(i, 4).toString());
                        }
                    }

                    for (int i = 0; i < tableTamanhos.getRowCount(); i++) {
                        if (tableTamanhos.getValueAt(i, 0).equals("")) {
                            ftd.create(nomeFerramenta, tableTamanhos.getValueAt(i, 2).toString());
                        }
                    }

                    JOptionPane.showMessageDialog(null, "Atualizado com sucesso.");
                } catch (SQLException e) {
                    String msg = "Erro ao atualizar Ferramenta.";
                    JOptionPane.showMessageDialog(null, msg + "\n" + e);

                    new Thread() {
                        @Override
                        public void run() {
                            SendEmail.EnviarErro2(msg, e);
                        }
                    }.start();
                }
            }

            lerFerramenta(txtNome.getText());

            lerFerramentas();
            VM1.lerFerramentas();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            String codigo = JOptionPane.showInputDialog(null, "Digite o código do tamanho.", "Código", JOptionPane.YES_NO_OPTION);

            DefaultTableModel model = (DefaultTableModel) tableTamanhos.getModel();
            model.addRow(new Object[]{
                "",
                false,
                codigo
            });
        } catch (Exception e) {
            String msg = "Erro.";
            JOptionPane.showMessageDialog(null, msg);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
//        try {
//            String nome = JOptionPane.showInputDialog(null, "Digite o nome da família.", "Nome", JOptionPane.YES_NO_OPTION);
//            String codigo = JOptionPane.showInputDialog(null, "Digite o código da família.", "Código", JOptionPane.YES_NO_OPTION);
//            String descricao = JOptionPane.showInputDialog(null, "Digite a descrição da família.", "Descrição", JOptionPane.YES_NO_OPTION);
//
//            DefaultTableModel model = (DefaultTableModel) tableFamilias.getModel();
//
//            model.addRow(new Object[]{
//                "",
//                false,
//                nome,
//                codigo,
//                descricao
//            });
//        } catch (Exception e) {
//            String msg = "Erro.";
//            JOptionPane.showMessageDialog(null, msg);
//        }
        NovaFamilia nf = new NovaFamilia();
        Telas.AparecerTela(nf);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tableFerramentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableFerramentasMouseClicked
        if (evt.getClickCount() == 2) {
            tabFerramentas.setSelectedIndex(1);

            idFerramenta = Integer.parseInt(tableFerramentas.getValueAt(tableFerramentas.getSelectedRow(), 0).toString());

            lerFerramenta(tableFerramentas.getValueAt(tableFerramentas.getSelectedRow(), 2).toString());
        }
    }//GEN-LAST:event_tableFerramentasMouseClicked

    private void tableFamiliasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableFamiliasMouseClicked
        if (evt.getClickCount() == 2) {
            NovaFamilia nf = new NovaFamilia();
            Telas.AparecerTela(nf);
            
            NovaFamilia.idFamilia = Integer.parseInt(tableFamilias.getValueAt(tableFamilias.getSelectedRow(), 0).toString());
            
            NovaFamilia.txtNome.setText(tableFamilias.getValueAt(tableFamilias.getSelectedRow(), 2).toString());
            NovaFamilia.txtCodigo.setText(tableFamilias.getValueAt(tableFamilias.getSelectedRow(), 3).toString());
            NovaFamilia.txtDescricao.setText(tableFamilias.getValueAt(tableFamilias.getSelectedRow(), 4).toString());
        }
    }//GEN-LAST:event_tableFamiliasMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int numTrue = 0;

        for (int i = 0; i < tableFamilias.getRowCount(); i++) {
            if (tableFamilias.getValueAt(i, 1).equals(true)) {
                numTrue++;
            }
        }

        if (numTrue == 0) {
            JOptionPane.showMessageDialog(null, "Nenhum registro selecionado.");
        } else {
            int resp = JOptionPane.showConfirmDialog(null, "Deseja deletar as famílias selecionadas?", "Deletar Famílias", JOptionPane.YES_NO_OPTION);

            if (resp == 0) {
                for (int i = 0; i < tableFamilias.getRowCount(); i++) {
                    if (tableFamilias.getValueAt(i, 1).equals(true)) {
                        int id = Integer.parseInt(tableFamilias.getValueAt(i, 0).toString());
                        try {
                            ffd.delete(id);

                            VM1.cbtipo.setSelectedIndex(0);
                        } catch (SQLException e) {
                            String msg = "Erro ao excluir.";
                            JOptionPane.showMessageDialog(null, msg + "\n" + e);

                            new Thread() {
                                @Override
                                public void run() {
                                    SendEmail.EnviarErro2(msg, e);
                                }
                            }.start();
                        }
                    }
                }

                lerFamilias(txtNome.getText());
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton1;
    public javax.swing.JButton jButton2;
    public javax.swing.JButton jButton3;
    public javax.swing.JButton jButton4;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JTabbedPane tabFerramentas;
    public static javax.swing.JTable tableFamilias;
    public javax.swing.JTable tableFerramentas;
    public javax.swing.JTable tableTamanhos;
    public javax.swing.JTextField txtDescricao;
    public static javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
