/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.servicos;

import Bean.ServicoOrcamentoItensBean;
import Bean.ServicoOrcamentoBean;
import Bean.ServicoOrcamentoDocumentosBean;
import Bean.ServicoPedidoBean;
import Bean.ServicoPedidoItensBean;
import DAO.ServicoOrcamentoItensDAO;
import DAO.ServicoOrcamentoDAO;
import DAO.ServicoOrcamentoDocumentosDAO;
import DAO.ServicoPedidoDAO;
import DAO.ServicoPedidoItensOrcamentoDAO;
import View.ProcurarCliente;
import View.comercial.ProcurarCondicaoDePagamento;
import View.comercial.ProcurarRepresentante;
import View.comercial.ProcurarVendedor;
import static View.TelaPrincipal.jDesktopPane1;
import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDesktopPane;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Marcos Filho
 */
public class OrcamentoServico extends javax.swing.JInternalFrame {

    /**
     * Creates new form OrcamentoServico
     */
    public OrcamentoServico() {
        initComponents();
        filltableorcamentoservico();
        tableitens();
        txtvalor();
    }

    public static void filltableorcamentoservico() {
        DefaultTableModel model = (DefaultTableModel) tableorcamentoservico.getModel();
        model.setNumRows(0);
        ServicoOrcamentoDAO sod = new ServicoOrcamentoDAO();

        for (ServicoOrcamentoBean sob : sod.read()) {
            model.addRow(new Object[]{
                sob.getId(),
                sob.getCliente(),
                sob.getStatus()
            });
        }
    }

    public static void tableitens() {
        DefaultTableModel modelti = (DefaultTableModel) tableitens.getModel();
        modelti.setNumRows(0);
    }

    public static void txtvalor() {
        if (tableitens.getRowCount() < 1) {
            txttotal.setText("");
        } else {
            float vt = 0;

            for (int i = 0; i < tableitens.getRowCount(); i++) {
                String v = tableitens.getValueAt(i, 6).toString().replace(".", "");
                String valor = v.replace(",", ".");
                float vp = Float.parseFloat(valor);
                vt = vt + vp;
            }
            DecimalFormat formatter = new DecimalFormat("#,###.00");
            String valorf = formatter.format(vt);
            txttotal.setText(String.valueOf(valorf));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jButton7 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        taborcamentos = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableorcamentoservico = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        PanelOrcamentoServico = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtnomecliente = new javax.swing.JTextField();
        BtnProcurar = new javax.swing.JButton();
        radioc = new javax.swing.JRadioButton();
        radionc = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtnumeroorcamento = new javax.swing.JTextField();
        txtstatus = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        txtvendedor = new javax.swing.JTextField();
        txtrepresentante = new javax.swing.JTextField();
        txtcondicao = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        BtnCondicao = new javax.swing.JButton();
        BtnRepresentante = new javax.swing.JButton();
        BtnVendedor = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableitens = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        txttotal = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtnotes = new javax.swing.JTextArea();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tabledocumentos = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();

        jButton7.setText("jButton7");

        setClosable(true);
        setTitle("Orçamento de Serviço");

        taborcamentos.setPreferredSize(new java.awt.Dimension(900, 500));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1007, 600));

        tableorcamentoservico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Cliente", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableorcamentoservico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableorcamentoservicoMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tableorcamentoservico);
        if (tableorcamentoservico.getColumnModel().getColumnCount() > 0) {
            tableorcamentoservico.getColumnModel().getColumn(0).setMinWidth(50);
            tableorcamentoservico.getColumnModel().getColumn(0).setPreferredWidth(50);
            tableorcamentoservico.getColumnModel().getColumn(0).setMaxWidth(50);
            tableorcamentoservico.getColumnModel().getColumn(1).setResizable(false);
            tableorcamentoservico.getColumnModel().getColumn(2).setResizable(false);
        }

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Procura"));

        jLabel4.setText("Pesquisa");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Status"));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Em Aberto", "Pedido Parcial", "Fechado", "Cancelado", "Todos" }));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 1060, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
                .addContainerGap())
        );

        taborcamentos.addTab("Lista de Orçamentos", jPanel1);

        PanelOrcamentoServico.setBackground(new java.awt.Color(255, 255, 255));
        PanelOrcamentoServico.setPreferredSize(new java.awt.Dimension(836, 600));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Cliente"));

        jLabel3.setText("Cliente");

        txtnomecliente.setEditable(false);
        txtnomecliente.setBackground(new java.awt.Color(255, 255, 255));

        BtnProcurar.setText("Procurar");
        BtnProcurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnProcurarActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioc);
        radioc.setSelected(true);
        radioc.setText("Cadastrado");
        radioc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiocActionPerformed(evt);
            }
        });

        buttonGroup1.add(radionc);
        radionc.setText("Não Cadastrado");
        radionc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioncActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(radioc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radionc))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtnomecliente, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnProcurar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioc)
                    .addComponent(radionc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtnomecliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnProcurar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Orçamento"));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Nº");

        txtnumeroorcamento.setEditable(false);
        txtnumeroorcamento.setBackground(new java.awt.Color(255, 255, 255));
        txtnumeroorcamento.setSelectionColor(new java.awt.Color(255, 255, 255));

        txtstatus.setEditable(false);
        txtstatus.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("Status");

        jButton4.setText("Imprimir");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtstatus, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                            .addComponent(txtnumeroorcamento)))
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtnumeroorcamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4)
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Comercial"));

        txtvendedor.setEditable(false);
        txtvendedor.setBackground(new java.awt.Color(255, 255, 255));

        txtrepresentante.setEditable(false);
        txtrepresentante.setBackground(new java.awt.Color(255, 255, 255));

        txtcondicao.setEditable(false);
        txtcondicao.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setText("Vendedor");

        jLabel6.setText("Representante");

        jLabel7.setText("Condição de Pagamento");

        BtnCondicao.setText("Procurar");
        BtnCondicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCondicaoActionPerformed(evt);
            }
        });

        BtnRepresentante.setText("Procurar");
        BtnRepresentante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRepresentanteActionPerformed(evt);
            }
        });

        BtnVendedor.setText("Procurar");
        BtnVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVendedorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtrepresentante, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                    .addComponent(txtvendedor)
                    .addComponent(txtcondicao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnCondicao)
                    .addComponent(BtnRepresentante)
                    .addComponent(BtnVendedor))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcondicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(BtnCondicao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtrepresentante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(BtnRepresentante))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtvendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(BtnVendedor))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Itens"));

        tableitens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "ID", "Código", "Descrição", "Qtde", "Valor Unitário R$", "Total R$", "Prazo de Entrega", "Pedido do Cliente", "DAS"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableitens.getTableHeader().setReorderingAllowed(false);
        tableitens.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableitensMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tableitensMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tableitens);
        if (tableitens.getColumnModel().getColumnCount() > 0) {
            tableitens.getColumnModel().getColumn(0).setMinWidth(30);
            tableitens.getColumnModel().getColumn(0).setPreferredWidth(30);
            tableitens.getColumnModel().getColumn(0).setMaxWidth(30);
            tableitens.getColumnModel().getColumn(1).setMinWidth(0);
            tableitens.getColumnModel().getColumn(1).setPreferredWidth(0);
            tableitens.getColumnModel().getColumn(1).setMaxWidth(0);
        }

        jButton2.setText("Incluir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        txttotal.setEditable(false);
        txttotal.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setText("Total: R$");

        jButton6.setText("Excluir");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jButton6)))
        );

        txtnotes.setColumns(20);
        txtnotes.setRows(5);
        jScrollPane7.setViewportView(txtnotes);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 1035, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Anotações", jPanel7);

        tabledocumentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "Id", "Descrição", "Local"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabledocumentos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabledocumentosMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(tabledocumentos);
        if (tabledocumentos.getColumnModel().getColumnCount() > 0) {
            tabledocumentos.getColumnModel().getColumn(0).setMinWidth(40);
            tabledocumentos.getColumnModel().getColumn(0).setMaxWidth(40);
            tabledocumentos.getColumnModel().getColumn(1).setMinWidth(0);
            tabledocumentos.getColumnModel().getColumn(1).setPreferredWidth(0);
            tabledocumentos.getColumnModel().getColumn(1).setMaxWidth(0);
            tabledocumentos.getColumnModel().getColumn(2).setMinWidth(500);
            tabledocumentos.getColumnModel().getColumn(2).setPreferredWidth(500);
            tabledocumentos.getColumnModel().getColumn(2).setMaxWidth(500);
        }

        jButton5.setText("Incluir");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton8.setText("Excluir");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 1035, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5)))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton8))
                .addContainerGap())
        );

        jTabbedPane2.addTab("Documentos", jPanel10);

        jButton3.setText("Criar Pedido");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton9.setText("Cancelar");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("Cancelar Orçamento");

        javax.swing.GroupLayout PanelOrcamentoServicoLayout = new javax.swing.GroupLayout(PanelOrcamentoServico);
        PanelOrcamentoServico.setLayout(PanelOrcamentoServicoLayout);
        PanelOrcamentoServicoLayout.setHorizontalGroup(
            PanelOrcamentoServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelOrcamentoServicoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelOrcamentoServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane2)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelOrcamentoServicoLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelOrcamentoServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelOrcamentoServicoLayout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelOrcamentoServicoLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton9)))))
                .addContainerGap())
        );
        PanelOrcamentoServicoLayout.setVerticalGroup(
            PanelOrcamentoServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelOrcamentoServicoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelOrcamentoServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(PanelOrcamentoServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3)
                    .addComponent(jButton9)
                    .addComponent(jButton10))
                .addContainerGap())
        );

        taborcamentos.addTab("Detalhes do Orçamento", PanelOrcamentoServico);

        jScrollPane3.setViewportView(taborcamentos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1087, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radioncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioncActionPerformed
        BtnProcurar.setEnabled(false);
        txtnomecliente.setEditable(true);
        txtnomecliente.requestFocus();
    }//GEN-LAST:event_radioncActionPerformed

    private void radiocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiocActionPerformed
        BtnProcurar.setEnabled(true);
    }//GEN-LAST:event_radiocActionPerformed

    private void BtnProcurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnProcurarActionPerformed
        ProcurarCliente p = new ProcurarCliente();
        JDesktopPane desk = this.getDesktopPane();
        desk.add(p);
        Dimension desktopsize = jDesktopPane1.getSize();
        Dimension jinternalframesize = p.getSize();
        p.setLocation((desktopsize.width - jinternalframesize.width) / 2, (desktopsize.height - jinternalframesize.height) / 2);
        p.setVisible(true);
    }//GEN-LAST:event_BtnProcurarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ItemOrcamentoServico ios = new ItemOrcamentoServico();
        JDesktopPane desk = this.getDesktopPane();
        desk.add(ios);
        Dimension i = ios.getSize();
        Dimension d = desk.getSize();
        ios.setLocation((d.width - i.width) / 2, (d.height - i.height) / 2);
        ios.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void BtnCondicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCondicaoActionPerformed
        ProcurarCondicaoDePagamento p = new ProcurarCondicaoDePagamento();
        JDesktopPane desk = this.getDesktopPane();
        desk.add(p);
        Dimension desktopsize = jDesktopPane1.getSize();
        Dimension jinternalframesize = p.getSize();
        p.setLocation((desktopsize.width - jinternalframesize.width) / 2, (desktopsize.height - jinternalframesize.height) / 2);
        p.setVisible(true);
    }//GEN-LAST:event_BtnCondicaoActionPerformed

    private void BtnRepresentanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRepresentanteActionPerformed
        ProcurarRepresentante p = new ProcurarRepresentante();
        JDesktopPane desk = this.getDesktopPane();
        desk.add(p);
        Dimension desktopsize = jDesktopPane1.getSize();
        Dimension jinternalframesize = p.getSize();
        p.setLocation((desktopsize.width - jinternalframesize.width) / 2, (desktopsize.height - jinternalframesize.height) / 2);
        p.setVisible(true);
    }//GEN-LAST:event_BtnRepresentanteActionPerformed

    private void BtnVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVendedorActionPerformed
        ProcurarVendedor p = new ProcurarVendedor();
        JDesktopPane desk = this.getDesktopPane();
        desk.add(p);
        Dimension desktopsize = jDesktopPane1.getSize();
        Dimension jinternalframesize = p.getSize();
        p.setLocation((desktopsize.width - jinternalframesize.width) / 2, (desktopsize.height - jinternalframesize.height) / 2);
        p.setVisible(true);
    }//GEN-LAST:event_BtnVendedorActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (txtnumeroorcamento.getText().equals("")) {
            ServicoOrcamentoBean sob = new ServicoOrcamentoBean();
            ServicoOrcamentoDAO sod = new ServicoOrcamentoDAO();
            String c;
            if (radioc.isSelected()) {
                c = "true";
            } else {
                c = "false";
            }
            sob.setCliente(txtnomecliente.getText());
            sob.setCondicao(txtcondicao.getText());
            sob.setRepresentante(txtrepresentante.getText());
            sob.setVendedor(txtvendedor.getText());
            sob.setNotes(txtnotes.getText());
            sob.setStatus("Ativo");
            sob.setClientecadastro(c);
            //cliente, condicao, representante, vendedor, notes, status, clientecadastro
            sod.create(sob);
            for (ServicoOrcamentoBean sob2 : sod.read()) {
                txtnumeroorcamento.setText(String.valueOf(sob2.getId()));
            }
            int nr = tableitens.getRowCount();
            for (int i = 0; i < nr; i++) {
                ServicoOrcamentoItensBean soib = new ServicoOrcamentoItensBean();
                ServicoOrcamentoItensDAO soid = new ServicoOrcamentoItensDAO();
                
                soib.setIdorcamento(txtnumeroorcamento.getText());
                soib.setCodigo(tableitens.getValueAt(i, 2).toString());
                soib.setDesc(tableitens.getValueAt(i, 3).toString());
                soib.setQtd(tableitens.getValueAt(i, 4).toString());
                soib.setValor(tableitens.getValueAt(i, 5).toString());
                soib.setTotal(tableitens.getValueAt(i, 6).toString());
                soib.setPrazo(tableitens.getValueAt(i, 7).toString());
                soib.setPedido(tableitens.getValueAt(i, 8).toString());
                soib.setDas(tableitens.getValueAt(i, 9).toString());
                //idorcamento, codigo, desc, qtd, valor, total, prazo, pedido, das
                
                soid.create(soib);
            }
            if (tabledocumentos.getRowCount() != 0) {
                int rc = tabledocumentos.getRowCount();
                for (int i = 0; i < rc; i++) {
                    ServicoOrcamentoDocumentosBean sodb = new ServicoOrcamentoDocumentosBean();
                    ServicoOrcamentoDocumentosDAO sodd = new ServicoOrcamentoDocumentosDAO();
                    
                    sodb.setIdorcamento(Integer.parseInt(txtnumeroorcamento.getText()));
                    sodb.setDescricao(tableitens.getValueAt(i, 2).toString());
                    sodb.setLocal(tableitens.getValueAt(i, 3).toString());
                    //idorcamento, descricao, local
                    
                    sodd.create(sodb);
                }
            }
            JOptionPane.showMessageDialog(rootPane, "Salvo com sucesso!");
        } else {
            ServicoOrcamentoBean sob = new ServicoOrcamentoBean();
            ServicoOrcamentoDAO sod = new ServicoOrcamentoDAO();

            String st = txtstatus.getText();

            String c;
            if (radioc.isSelected()) {
                c = "true";
            } else {
                c = "false";
            }

            sob.setCliente(txtnomecliente.getText());
            sob.setCondicao(txtcondicao.getText());
            sob.setRepresentante(txtrepresentante.getText());
            sob.setVendedor(txtvendedor.getText());
            sob.setNotes(txtnotes.getText());
            sob.setStatus(st);
            sob.setClientecadastro(c);
            sob.setId(Integer.parseInt(txtnumeroorcamento.getText()));
            //cliente, condicao, representante, vendedor, notes, status, clientecadastro

            sod.update(sob);

            int nr = tableitens.getRowCount();
            for (int i = 0; i < nr; i++) {
                ServicoOrcamentoItensBean soib = new ServicoOrcamentoItensBean();
                ServicoOrcamentoItensDAO soid = new ServicoOrcamentoItensDAO();

                if (tableitens.getValueAt(i, 1).equals("")) {
                    soib.setIdorcamento(txtnumeroorcamento.getText());
                    soib.setCodigo(tableitens.getValueAt(i, 2).toString());
                    soib.setDesc(tableitens.getValueAt(i, 3).toString());
                    soib.setQtd(tableitens.getValueAt(i, 4).toString());
                    soib.setValor(tableitens.getValueAt(i, 5).toString());
                    soib.setTotal(tableitens.getValueAt(i, 6).toString());
                    soib.setPrazo(tableitens.getValueAt(i, 7).toString());
                    soib.setPedido(tableitens.getValueAt(i, 8).toString());
                    soib.setDas(tableitens.getValueAt(i, 9).toString());
                    //idorcamento, codigo, desc, qtd, valor, total, prazo, pedido, das

                    soid.create(soib);
                } else {
                    soib.setCodigo(tableitens.getValueAt(i, 2).toString());
                    soib.setDesc(tableitens.getValueAt(i, 3).toString());
                    soib.setQtd(tableitens.getValueAt(i, 4).toString());
                    soib.setValor(tableitens.getValueAt(i, 5).toString());
                    soib.setTotal(tableitens.getValueAt(i, 6).toString());
                    soib.setPrazo(tableitens.getValueAt(i, 7).toString());
                    soib.setPedido(tableitens.getValueAt(i, 8).toString());
                    soib.setDas(tableitens.getValueAt(i, 9).toString());
                    soib.setId(Integer.parseInt(tableitens.getValueAt(i, 1).toString()));
                    //codigo, descricao , qtd , valor , total , prazo , pedido , das, id

                    soid.update(soib);
                }
            }
            int rctd = tabledocumentos.getRowCount();
            if (rctd != 0) {
                for (int i = 0; i < rctd; i++) {
                    if (tabledocumentos.getValueAt(i, 1).equals("")) {
                        ServicoOrcamentoDocumentosBean sodb = new ServicoOrcamentoDocumentosBean();
                        ServicoOrcamentoDocumentosDAO sodd = new ServicoOrcamentoDocumentosDAO();

                        sodb.setIdorcamento(Integer.parseInt(txtnumeroorcamento.getText()));
                        sodb.setDescricao(tabledocumentos.getValueAt(i, 2).toString());
                        sodb.setLocal(tabledocumentos.getValueAt(i, 3).toString());
                        //idorcamento, descricao, local

                        sodd.create(sodb);
                    } else {
                        ServicoOrcamentoDocumentosBean sodb = new ServicoOrcamentoDocumentosBean();
                        ServicoOrcamentoDocumentosDAO sodd = new ServicoOrcamentoDocumentosDAO();

                        sodb.setIdorcamento(Integer.parseInt(txtnumeroorcamento.getText()));
                        sodb.setDescricao(tabledocumentos.getValueAt(i, 2).toString());
                        sodb.setLocal(tabledocumentos.getValueAt(i, 3).toString());
                        sodb.setId(Integer.parseInt(tabledocumentos.getValueAt(i, 1).toString()));
                        //idorcamento, descricao, local, id

                        sodd.update(sodb);
                    }
                }
            }
            JOptionPane.showMessageDialog(rootPane, "Atualizado com sucesso!");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        int i = JOptionPane.showConfirmDialog(rootPane, "Deseja excluir os itens selecionados?", "Excluir itens", JOptionPane.YES_NO_OPTION);
        DefaultTableModel model = (DefaultTableModel) tableitens.getModel();
        if (tableitens.getRowCount() < 1) {
            JOptionPane.showMessageDialog(rootPane, "Não existem itens para excluir.");
        } else if (i == 0) {
            for (int j = 0; j < tableitens.getRowCount(); j++) {
                String v = tableitens.getValueAt(j, 0).toString();
                if (v.equals("true")) {
                    model.removeRow(j);
                }
            }
        }
        txtvalor();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if (txtnumeroorcamento.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Selecione um orçamento antes!");
        } else {
            Documentos d = new Documentos();
            JDesktopPane desk = this.getDesktopPane();
            desk.add(d);
            Dimension desktopsize = jDesktopPane1.getSize();
            Dimension jinternalframesize = d.getSize();
            d.setLocation((desktopsize.width - jinternalframesize.width) / 2, (desktopsize.height - jinternalframesize.height) / 2);
            d.setVisible(true);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void tableitensMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableitensMouseClicked
        if (evt.getButton() == 1) {
            if (evt.getClickCount() == 2) {
                ItemOrcamentoServico ios = new ItemOrcamentoServico();
                JDesktopPane desk = this.getDesktopPane();
                desk.add(ios);
                Dimension i = ios.getSize();
                Dimension d = desk.getSize();
                ios.setLocation((d.width - i.width) / 2, (d.height - i.height) / 2);
                ios.setVisible(true);
                if (tableitens.getValueAt(tableitens.getSelectedRow(), 2).equals("")) {
                    ItemOrcamentoServico.jRadioButton2.setSelected(true);
                    ItemOrcamentoServico.btnprocurar.setEnabled(false);
                    ItemOrcamentoServico.txtdesc.setEditable(true);
                }
                ItemOrcamentoServico.txtrow.setText(String.valueOf(tableitens.getSelectedRow()));
                ItemOrcamentoServico.txtid.setText(tableitens.getValueAt(tableitens.getSelectedRow(), 1).toString());
                ItemOrcamentoServico.txtcodigo.setText(tableitens.getValueAt(tableitens.getSelectedRow(), 2).toString());
                ItemOrcamentoServico.txtdesc.setText(tableitens.getValueAt(tableitens.getSelectedRow(), 3).toString());
                ItemOrcamentoServico.txtqtd.setText(tableitens.getValueAt(tableitens.getSelectedRow(), 4).toString());
                ItemOrcamentoServico.txtvalor.setText(tableitens.getValueAt(tableitens.getSelectedRow(), 5).toString());
                ItemOrcamentoServico.txtprazo.setText(tableitens.getValueAt(tableitens.getSelectedRow(), 7).toString());
                ItemOrcamentoServico.txtpedido.setText(tableitens.getValueAt(tableitens.getSelectedRow(), 8).toString());
            }
        }
        if (evt.getButton() == 3) {
            JPopupMenu menu = new JPopupMenu();
            JMenuItem das = new JMenuItem("Abrir DAS");

            das.addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent ae) {
                    String DAS = tableitens.getValueAt(tableitens.getSelectedRow(), 9).toString();
                    if (DAS.equals("")) {
                        JOptionPane.showMessageDialog(rootPane, "Produto sem DAS");
                    } else {
                        JOptionPane.showMessageDialog(null, DAS);
                    }
                }
            });

            menu.add(das);

            menu.show(evt.getComponent(), evt.getPoint().x, evt.getPoint().y);
        }
    }//GEN-LAST:event_tableitensMouseClicked

    private void tableorcamentoservicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableorcamentoservicoMouseClicked
        if (evt.getClickCount() == 2) {
            taborcamentos.setSelectedIndex(1);
            txtnumeroorcamento.setText(tableorcamentoservico.getValueAt(tableorcamentoservico.getSelectedRow(), 0).toString());

            ServicoOrcamentoDAO sod = new ServicoOrcamentoDAO();

            for (ServicoOrcamentoBean sob : sod.click(Integer.parseInt(txtnumeroorcamento.getText()))) {
                if (sob.getClientecadastro().equals("true")) {
                    radioc.setSelected(true);
                } else {
                    radionc.setSelected(true);
                }
                txtnomecliente.setText(sob.getCliente());
                txtcondicao.setText(sob.getCondicao());
                txtrepresentante.setText(sob.getRepresentante());
                txtvendedor.setText(sob.getVendedor());
                txtstatus.setText(sob.getStatus());
                txtnotes.setText(sob.getNotes());
            }

            DefaultTableModel model = (DefaultTableModel) tableitens.getModel();
            model.setNumRows(0);
            ServicoOrcamentoItensDAO iosd = new ServicoOrcamentoItensDAO();

            for (ServicoOrcamentoItensBean iosb : iosd.readitens(txtnumeroorcamento.getText())) {
                model.addRow(new Object[]{
                    false,
                    iosb.getId(),
                    iosb.getCodigo(),
                    iosb.getDesc(),
                    iosb.getQtd(),
                    iosb.getValor(),
                    iosb.getTotal(),
                    iosb.getPrazo(),
                    iosb.getPedido(),
                    iosb.getDas()
                });
            }
            
            txtvalor();

            DefaultTableModel modeldoc = (DefaultTableModel) tabledocumentos.getModel();
            modeldoc.setNumRows(0);
            ServicoOrcamentoDocumentosDAO sodd = new ServicoOrcamentoDocumentosDAO();

            for (ServicoOrcamentoDocumentosBean sodb : sodd.readitens(txtnumeroorcamento.getText())) {
                modeldoc.addRow(new Object[]{
                    false,
                    sodb.getId(),
                    sodb.getDescricao(),
                    sodb.getLocal(),});
            }
        }
    }//GEN-LAST:event_tableorcamentoservicoMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        JOptionPane.showMessageDialog(rootPane, "Em breve!");
//        try {
//            new JasperOrcamentoServico().gerar("Reports/orcamento_servico2.jrxml");
//        } catch (ClassNotFoundException | SQLException e) {
//            JOptionPane.showMessageDialog(rootPane, "Erro ao mostrar relatório!\n" + e);
//        } catch (JRException ex) {
//            Logger.getLogger(OrcamentoServico.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void tableitensMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableitensMouseReleased
        int r = tableitens.rowAtPoint(evt.getPoint());
        if (r >= 0 && r < tableitens.getRowCount()) {
            tableitens.setRowSelectionInterval(r, r);
        } else {
            tableitens.clearSelection();
        }
    }//GEN-LAST:event_tableitensMouseReleased

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void tabledocumentosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabledocumentosMouseClicked
        if (evt.getClickCount() == 2) {
            Desktop desk = Desktop.getDesktop();
            try {
                desk.open(new File((String) tabledocumentos.getValueAt(tabledocumentos.getSelectedRow(), 3)));
            } catch (IOException ex) {
                Logger.getLogger(Documentos.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_tabledocumentosMouseClicked

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        DefaultTableModel model = (DefaultTableModel) tabledocumentos.getModel();
        if (tabledocumentos.getRowCount() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Não existem itens para excluir");
        } else {
            int resp = JOptionPane.showConfirmDialog(rootPane, "Excluir documentos selecionados?", "Excluir documentos", JOptionPane.OK_CANCEL_OPTION);
            if (resp == 0) {
                int nr = tabledocumentos.getRowCount();
                for (int i = 0; i < nr; i++) {
                    if (tabledocumentos.getValueAt(i, 0).equals(true)) {
                        File file = new File((String) tabledocumentos.getValueAt(i, 3));
                        try {
                            Files.delete(file.toPath());
                        } catch (IOException ex) {
                            Logger.getLogger(OrcamentoServico.class.getName()).log(Level.SEVERE, null, ex);
                            JOptionPane.showMessageDialog(rootPane, "Erro!\n" + ex);
                        }

                        ServicoOrcamentoDocumentosBean sodb = new ServicoOrcamentoDocumentosBean();
                        ServicoOrcamentoDocumentosDAO sodd = new ServicoOrcamentoDocumentosDAO();

                        sodb.setId(Integer.parseInt(tabledocumentos.getValueAt(i, 1).toString()));
                        //id

                        sodd.delete(sodb);

                        model.removeRow(i);
                    }
                }
            }
        }

    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (txtnumeroorcamento.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Escolha um orçamento ou salve este primeiro!");
        } else {
            int resp = JOptionPane.showConfirmDialog(rootPane, "Deseja gerar um pedido com os dados deste orçamento?", "Gerar pedido", JOptionPane.OK_CANCEL_OPTION);
            if (resp == 0) {
                ServicoPedidoBean spb = new ServicoPedidoBean();
                ServicoPedidoDAO spd = new ServicoPedidoDAO();

                spb.setIdorcamento(Integer.parseInt(txtnumeroorcamento.getText()));
                spb.setCliente(txtnomecliente.getText());
                spb.setCondicao(txtcondicao.getText());
                spb.setRepresentante(txtrepresentante.getText());
                spb.setVendedor(txtvendedor.getText());
                spb.setNotes(txtnotes.getText());
                spb.setStatus("Aberto");
                spb.setNfcliente("");
//              idorcamento, cliente, condicao, representante, vendedor, notes, status, nfcliente

                spd.create(spb);

                int numpedido = 0;
                ServicoPedidoDAO spdd = new ServicoPedidoDAO();
                for (ServicoPedidoBean spbb : spdd.readcreated(txtnomecliente.getText(), txtnumeroorcamento.getText())) {
                    numpedido = spbb.getId();
                }

                int rc = tableitens.getRowCount();
                for (int i = 0; i < rc; i++) {
                    if (tableitens.getValueAt(rc, 0) == "true") {
                        ServicoPedidoItensBean spib = new ServicoPedidoItensBean();
                        ServicoPedidoItensOrcamentoDAO spid = new ServicoPedidoItensOrcamentoDAO();

                        spib.setIdpedido(numpedido);
                        spib.setCodigo(tableitens.getValueAt(rc, 2).toString());
                        spib.setDescricao(tableitens.getValueAt(rc, 3).toString());
                        spib.setQtde(tableitens.getValueAt(rc, 4).toString());
                        spib.setValor(tableitens.getValueAt(rc, 5).toString());
                        spib.setTotal(tableitens.getValueAt(rc, 6).toString());
                        spib.setPrazo(tableitens.getValueAt(rc, 7).toString());
                        spib.setPedidocliente(tableitens.getValueAt(rc, 8).toString());
                        spib.setNf("");
//                      idpedido, codigo, descricao, qtde, valor, total, prazo, pedidocliente, nf

                        spid.create(spib);
                    }
                }
                if (tabledocumentos.getRowCount() > 0) {
                    int respdoc = JOptionPane.showConfirmDialog(rootPane, "Deseja enviar os documentos deste orçamento para o pedido?", "Gerar pedido com documentos", JOptionPane.OK_CANCEL_OPTION);
                    if (respdoc == 0) {
                        JOptionPane.showMessageDialog(rootPane, "Em breve!");
                    }
                }
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCondicao;
    private javax.swing.JButton BtnProcurar;
    private javax.swing.JButton BtnRepresentante;
    private javax.swing.JButton BtnVendedor;
    private javax.swing.JPanel PanelOrcamentoServico;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JRadioButton radioc;
    private javax.swing.JRadioButton radionc;
    public static javax.swing.JTable tabledocumentos;
    public static javax.swing.JTable tableitens;
    public static javax.swing.JTable tableorcamentoservico;
    private javax.swing.JTabbedPane taborcamentos;
    public static javax.swing.JTextField txtcondicao;
    public static javax.swing.JTextField txtnomecliente;
    public static javax.swing.JTextArea txtnotes;
    public static javax.swing.JTextField txtnumeroorcamento;
    public static javax.swing.JTextField txtrepresentante;
    private javax.swing.JTextField txtstatus;
    public static javax.swing.JTextField txttotal;
    public static javax.swing.JTextField txtvendedor;
    // End of variables declaration//GEN-END:variables
}
