/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.TI;

import Bean.SenhasAcessoBean;
import Bean.SenhasBean;
import Connection.Session;
import DAO.SenhasAcessoDAO;
import DAO.SenhasDAO;
import Methods.Telas;
import View.Geral.ProcurarUser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Marcos Filho
 */
public class Senhas extends javax.swing.JInternalFrame {

    /**
     * Creates new form Senhas
     */
    static SenhasDAO sd = new SenhasDAO();
    static SenhasBean sb = new SenhasBean();
    static SenhasAcessoBean sab = new SenhasAcessoBean();
    static SenhasAcessoDAO sad = new SenhasAcessoDAO();

    String[] acesso;

    public Senhas() {
        initComponents();
        readsenhas();
    }

    public static void readsenhas() {
        DefaultTableModel model = (DefaultTableModel) tablesenhas.getModel();
        model.setNumRows(0);

        SenhasDAO sd = new SenhasDAO();

        sd.read().forEach(sb -> {
            model.addRow(new Object[]{
                sb.getId(),
                false,
                sb.getNome()
            });
        });
    }

    public static void readAcessos() {
        DefaultTableModel modelacesso = (DefaultTableModel) tableacesso.getModel();
        modelacesso.setNumRows(0);

        sad.click(Integer.parseInt(txtid.getText())).forEach(sab -> {
            modelacesso.addRow(new Object[]{
                sab.getId(),
                false,
                sab.getNome()
            });
        });
    }

    public static void zeracampos() {
        txtid.setText("");
        txtnome.setText("");
        txtlogin.setText("");
        txtsenha.setText("");
        txtsite.setText("");

        DefaultTableModel model = (DefaultTableModel) tableacesso.getModel();
        model.setNumRows(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabsenhas = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablesenhas = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        txtpesquisa = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtnome = new javax.swing.JTextField();
        txtlogin = new javax.swing.JTextField();
        txtsenha = new javax.swing.JTextField();
        txtsite = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableacesso = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setClosable(true);
        setTitle("Senhas");

        tabsenhas.setName("tabsenhas"); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setName("jPanel1"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        tablesenhas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "", "Nome"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Boolean.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablesenhas.setName("tablesenhas"); // NOI18N
        tablesenhas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablesenhasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablesenhas);
        if (tablesenhas.getColumnModel().getColumnCount() > 0) {
            tablesenhas.getColumnModel().getColumn(0).setMinWidth(0);
            tablesenhas.getColumnModel().getColumn(0).setPreferredWidth(0);
            tablesenhas.getColumnModel().getColumn(0).setMaxWidth(0);
            tablesenhas.getColumnModel().getColumn(1).setMinWidth(35);
            tablesenhas.getColumnModel().getColumn(1).setPreferredWidth(35);
            tablesenhas.getColumnModel().getColumn(1).setMaxWidth(35);
        }

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesquisa"));
        jPanel3.setName("jPanel3"); // NOI18N

        txtpesquisa.setName("txtpesquisa"); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtpesquisa)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtpesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabsenhas.addTab("Cadastro de Senhas", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setName("jPanel2"); // NOI18N

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Informações de Login"));
        jPanel4.setName("jPanel4"); // NOI18N

        jLabel1.setLabelFor(txtnome);
        jLabel1.setText("Nome");
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setLabelFor(txtlogin);
        jLabel2.setText("Login");
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setLabelFor(txtsenha);
        jLabel3.setText("Senha");
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel4.setLabelFor(txtsite);
        jLabel4.setText("Site");
        jLabel4.setName("jLabel4"); // NOI18N

        txtnome.setName("txtnome"); // NOI18N

        txtlogin.setName("txtlogin"); // NOI18N

        txtsenha.setName("txtsenha"); // NOI18N

        txtsite.setName("txtsite"); // NOI18N

        jLabel5.setLabelFor(txtid);
        jLabel5.setText("ID");
        jLabel5.setName("jLabel5"); // NOI18N

        txtid.setEnabled(false);
        txtid.setName("txtid"); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtsenha))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtsite, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 68, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(txtlogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtsite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setText("Salvar");
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Acesso"));
        jPanel5.setName("jPanel5"); // NOI18N

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        tableacesso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "", "Nome"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Boolean.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableacesso.setName("tableacesso"); // NOI18N
        jScrollPane2.setViewportView(tableacesso);
        if (tableacesso.getColumnModel().getColumnCount() > 0) {
            tableacesso.getColumnModel().getColumn(0).setMinWidth(0);
            tableacesso.getColumnModel().getColumn(0).setPreferredWidth(0);
            tableacesso.getColumnModel().getColumn(0).setMaxWidth(0);
            tableacesso.getColumnModel().getColumn(1).setMinWidth(35);
            tableacesso.getColumnModel().getColumn(1).setPreferredWidth(35);
            tableacesso.getColumnModel().getColumn(1).setMaxWidth(35);
        }

        jButton2.setText("Adicionar Acesso");
        jButton2.setName("jButton2"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Excluir Acesso");
        jButton3.setName("jButton3"); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        tabsenhas.addTab("Detalhes da Senha", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabsenhas)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabsenhas)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (txtnome.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Digite um nome.");
            txtnome.requestFocus();
        } else if (txtlogin.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Digite um login.");
            txtlogin.requestFocus();
        } else if (txtsenha.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Digite uma senha.");
            txtsenha.requestFocus();
        } else if (tableacesso.getRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "Adicione 1 funcionário.");
            ProcurarUser pu = new ProcurarUser("Senhas");
            Telas.AparecerTela(pu);
        } else if (txtid.getText().equals("")) {
            //Se não tem ID, cria Senha
            sb.setNome(txtnome.getText());
            sb.setLogin(txtlogin.getText());
            sb.setSenha(txtsenha.getText());
            sb.setSite(txtsite.getText());

            //login, nome, senha, site
            sd.create(sb);

            for (int i = 0; i < tableacesso.getRowCount(); i++) {
                sab.setNome(tableacesso.getValueAt(i, 2).toString());
                sab.setIdsenha(Integer.parseInt(txtid.getText()));

                //idsenha, nome
                sad.create(sab);
            }
            JOptionPane.showMessageDialog(null, "Salvo com sucesso!");

        } else {
            //Se tem ID, atualiza Senha
            sb.setId(Integer.parseInt(txtid.getText()));
            sb.setNome(txtnome.getText());
            sb.setLogin(txtlogin.getText());
            sb.setSenha(txtsenha.getText());
            sb.setSite(txtsite.getText());

            //login = ?, senha = ?, nome = ?, site = ? WHERE id = ?
            sd.update(sb);

            for (int i = 0; i < tableacesso.getRowCount(); i++) {
                if (tableacesso.getValueAt(i, 0).equals("")) {
                    sab.setIdsenha(Integer.parseInt(txtid.getText()));
                    sab.setNome(tableacesso.getValueAt(i, 2).toString());

                    //idsenha, nome
                    sad.create(sab);
                }
            }

            JOptionPane.showMessageDialog(null, "Atualizado com sucesso!");
        }
        readsenhas();
        tabsenhas.setSelectedIndex(0);
        zeracampos();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tablesenhasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablesenhasMouseClicked
        if (evt.getClickCount() == 2) {
//            SenhasBean sb = SenhasDAO.getInstance().getById(Integer.parseInt(tablesenhas.getValueAt(tablesenhas.getSelectedRow(), 0).toString()));
//            jTabbedPane1.setSelectedIndex(1);
//            txtid.setText(String.valueOf(sb.getId()));
//            txtnome.setText(sb.getNome());
//            txtlogin.setText(sb.getLogin());
//            txtsenha.setText(sb.getSenha());
//            txtsite.setText(sb.getSite());
            int id = Integer.parseInt(tablesenhas.getValueAt(tablesenhas.getSelectedRow(), 0).toString());

            acesso = new String[sad.click(id).size()];

            int index = 0;

            for (SenhasAcessoBean sab : sad.click(id)) {
                acesso[index] = sab.getNome();
                index += 1;
            }

            for (int i = 0; i < acesso.length; i++) {
                if (Session.nome.equals(acesso[i])) {
                    tabsenhas.setSelectedIndex(1);

                    sd.click(id).forEach(sb -> {
                        txtid.setText(String.valueOf(sb.getId()));
                        txtnome.setText(sb.getNome());
                        txtlogin.setText(sb.getLogin());
                        txtsenha.setText(sb.getSenha());
                        txtsite.setText(sb.getSite());
                    });

                    readAcessos();
                    break;
                } else {
                    if (i == acesso.length - 1) {
                        JOptionPane.showMessageDialog(null, "Você não possui acesso a esta senha.");
                    }
                }
            }
        }
    }//GEN-LAST:event_tablesenhasMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ProcurarUser pu = new ProcurarUser(this.getClass().getSimpleName());
        Telas.AparecerTela(pu);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int numtrue = 0;
        int rc = tableacesso.getRowCount();
        for (int i = 0; i < rc; i++) {
            if (tableacesso.getValueAt(i, 1).equals(true)) {
                numtrue++;
            }
        }
        if (numtrue == 0) {
            JOptionPane.showMessageDialog(null, "Não foram selecionados usuários.");
        } else if (txtid.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Salve a senha primeiro.");
        } else {
            int resp = JOptionPane.showConfirmDialog(null, "Deseja retirar o acesso deste(s) usuário(s)?", "Excluir acesso", JOptionPane.YES_NO_OPTION);
            if (resp == 0) {
                for (int i = 0; i < rc; i++) {
                    if (tableacesso.getValueAt(i, 1).equals(true)) {
                        sab.setId(rc);

                        //id = ?
                        sad.delete(sab);
                    }
                }
                JOptionPane.showMessageDialog(null, "Excluído com sucesso!");
                readAcessos();
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton1;
    public javax.swing.JButton jButton2;
    public javax.swing.JButton jButton3;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JPanel jPanel3;
    public javax.swing.JPanel jPanel4;
    public javax.swing.JPanel jPanel5;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTable tableacesso;
    public static javax.swing.JTable tablesenhas;
    public javax.swing.JTabbedPane tabsenhas;
    public static javax.swing.JTextField txtid;
    public static javax.swing.JTextField txtlogin;
    public static javax.swing.JTextField txtnome;
    public static javax.swing.JTextField txtpesquisa;
    public static javax.swing.JTextField txtsenha;
    public static javax.swing.JTextField txtsite;
    // End of variables declaration//GEN-END:variables
}
