/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.administracao;

import Bean.GrupoDeUsuariosBean;
import DAO.GrupoDeUsuariosDAO;
import DAO.MenusDAO;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Marcos Filho
 */
public class GrupoDeUsuarios extends javax.swing.JInternalFrame {

    /**
     * Creates new form GrupoDeUsuarios
     */
    public GrupoDeUsuarios() {
        initComponents();
        readtablegrupos();
        readtablepermissoes();
    }

    public static void readtablegrupos() {
        DefaultTableModel modelo = (DefaultTableModel) tablegrupos.getModel();
        modelo.setNumRows(0);
        GrupoDeUsuariosDAO gud = new GrupoDeUsuariosDAO();

        gud.read().forEach((c) -> {
            modelo.addRow(new Object[]{
                c.getId(),
                c.getNome()
            });
        });
    }

    public static void readtablepermissoes() {
        DefaultTableModel modelo = (DefaultTableModel) tablepermissoes.getModel();
        modelo.setNumRows(0);
        MenusDAO ud = new MenusDAO();

        ud.read().forEach((c) -> {
            modelo.addRow(new Object[]{
                false,
                c.getNome()
            });
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabgrupos = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablegrupos = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtnomegrupo = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablepermissoes = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtidgrupo = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setTitle("Grupo de Usuários");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tablegrupos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablegrupos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablegruposMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablegrupos);
        if (tablegrupos.getColumnModel().getColumnCount() > 0) {
            tablegrupos.getColumnModel().getColumn(0).setMinWidth(30);
            tablegrupos.getColumnModel().getColumn(0).setPreferredWidth(30);
            tablegrupos.getColumnModel().getColumn(0).setMaxWidth(30);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabgrupos.addTab("Lista de Grupos", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados Grupo"));

        jLabel1.setText("Nome:");

        tablepermissoes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Permissão", "Nome"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablepermissoes.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tablepermissoes);
        if (tablepermissoes.getColumnModel().getColumnCount() > 0) {
            tablepermissoes.getColumnModel().getColumn(0).setMinWidth(100);
            tablepermissoes.getColumnModel().getColumn(0).setPreferredWidth(100);
            tablepermissoes.getColumnModel().getColumn(0).setMaxWidth(100);
            tablepermissoes.getColumnModel().getColumn(1).setResizable(false);
        }

        jLabel2.setText("ID");

        txtidgrupo.setEditable(false);
        txtidgrupo.setBackground(new java.awt.Color(255, 255, 255));

        jButton2.setText("Marcar todos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Desmarcar todos");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtidgrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtnomegrupo))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtnomegrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtidgrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        jButton1.setText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        tabgrupos.addTab("Detalhes Grupo", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabgrupos)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabgrupos)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablegruposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablegruposMouseClicked
        if (evt.getClickCount() == 2) {
            tabgrupos.setSelectedIndex(1);
            txtidgrupo.setText(tablegrupos.getValueAt(tablegrupos.getSelectedRow(), 0).toString());

            GrupoDeUsuariosDAO gud = new GrupoDeUsuariosDAO();

            gud.readgrupocadastrado().forEach((ub) -> {
                txtnomegrupo.setText(ub.getNome());
                Boolean status;
                if (ub.getMenuadministracao().equals("false")) {
                    status = false;
                } else {
                    status = true;
                }
                tablepermissoes.setValueAt(status, 0, 0);
                if (ub.getSubmenuusuarios().equals("false")) {
                    status = false;
                } else {
                    status = true;
                }
                tablepermissoes.setValueAt(status, 1, 0);
                if (ub.getSubmenugrupodeusuarios().equals("false")) {
                    status = false;
                } else {
                    status = true;
                }
                tablepermissoes.setValueAt(status, 2, 0);
                if (ub.getSubmenurepresentantes().equals("false")) {
                    status = false;
                } else {
                    status = true;
                }
                tablepermissoes.setValueAt(status, 3, 0);
                if (ub.getMenucomercial().equals("false")) {
                    status = false;
                } else {
                    status = true;
                }
                tablepermissoes.setValueAt(status, 4, 0);
                if (ub.getSubmenuclientes().equals("false")) {
                    status = false;
                } else {
                    status = true;
                }
                tablepermissoes.setValueAt(status, 5, 0);
                if (ub.getSubmenugrupodeclientes().equals("false")) {
                    status = false;
                } else {
                    status = true;
                }
                tablepermissoes.setValueAt(status, 6, 0);
                if (ub.getSubmenucondicoesdepagamento().equals("false")) {
                    status = false;
                } else {
                    status = true;
                }
                tablepermissoes.setValueAt(status, 7, 0);
                if (ub.getMenuvendas().equals("false")) {
                    status = false;
                } else {
                    status = true;
                }
                tablepermissoes.setValueAt(status, 8, 0);
                if (ub.getSubmenuorcamentosvenda().equals("false")) {
                    status = false;
                } else {
                    status = true;
                }
                tablepermissoes.setValueAt(status, 9, 0);
                if (ub.getSubmenupedidosvenda().equals("false")) {
                    status = false;
                } else {
                    status = true;
                }
                tablepermissoes.setValueAt(status, 10, 0);
                if (ub.getSubmenuops().equals("false")) {
                    status = false;
                } else {
                    status = true;
                }
                tablepermissoes.setValueAt(status, 11, 0);
                if (ub.getSubmenuprodutosvenda().equals("false")) {
                    status = false;
                } else {
                    status = true;
                }
                tablepermissoes.setValueAt(status, 12, 0);
                if (ub.getMenuservicos().equals("false")) {
                    status = false;
                } else {
                    status = true;
                }
                tablepermissoes.setValueAt(status, 13, 0);
                if (ub.getSubmenuorcamentosservico().equals("false")) {
                    status = false;
                } else {
                    status = true;
                }
                tablepermissoes.setValueAt(status, 14, 0);
                if (ub.getSubmenupedidosservico().equals("false")) {
                    status = false;
                } else {
                    status = true;
                }
                tablepermissoes.setValueAt(status, 15, 0);
                if (ub.getSubmenuoss().equals("false")) {
                    status = false;
                } else {
                    status = true;
                }
                tablepermissoes.setValueAt(status, 16, 0);
                if (ub.getSubmenuprodutosservico().equals("false")) {
                    status = false;
                } else {
                    status = true;
                }
                tablepermissoes.setValueAt(status, 17, 0);
                if (ub.getMenuconfiguracoes().equals("false")) {
                    status = false;
                } else {
                    status = true;
                }
                tablepermissoes.setValueAt(status, 18, 0);
                if (ub.getSubmenumenus().equals("false")) {
                    status = false;
                } else {
                    status = true;
                }
                tablepermissoes.setValueAt(status, 19, 0);
                if (ub.getMenucompras().equals("false")) {
                    status = false;
                } else {
                    status = true;
                }
                tablepermissoes.setValueAt(status, 20, 0);
                if (ub.getSubmenusolicitacaodecompras().equals("false")) {
                    status = false;
                } else {
                    status = true;
                }
                tablepermissoes.setValueAt(status, 21, 0);
                if (ub.getSubmenupedidodecompras().equals("false")) {
                    status = false;
                } else {
                    status = true;
                }
                tablepermissoes.setValueAt(status, 22, 0);
                if (ub.getSubmenuinsumos().equals("false")) {
                    status = false;
                } else {
                    status = true;
                }
                tablepermissoes.setValueAt(status, 23, 0);
            });

        }
    }//GEN-LAST:event_tablegruposMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (txtnomegrupo.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Coloque um nome!");
        } else if (txtidgrupo.getText().equals("")) {
            GrupoDeUsuariosBean gub = new GrupoDeUsuariosBean();
            GrupoDeUsuariosDAO gudao = new GrupoDeUsuariosDAO();

            gub.setNome(txtnomegrupo.getText());
            gub.setMenuadministracao(tablepermissoes.getValueAt(0, 0).toString());
            gub.setSubmenuusuarios(tablepermissoes.getValueAt(1, 0).toString());
            gub.setSubmenugrupodeusuarios(tablepermissoes.getValueAt(2, 0).toString());
            gub.setSubmenurepresentantes(tablepermissoes.getValueAt(3, 0).toString());
            gub.setMenucomercial(tablepermissoes.getValueAt(4, 0).toString());
            gub.setSubmenuclientes(tablepermissoes.getValueAt(5, 0).toString());
            gub.setSubmenugrupodeclientes(tablepermissoes.getValueAt(6, 0).toString());
            gub.setSubmenucondicoesdepagamento(tablepermissoes.getValueAt(7, 0).toString());
            gub.setMenuvendas(tablepermissoes.getValueAt(8, 0).toString());
            gub.setSubmenuorcamentosvenda(tablepermissoes.getValueAt(9, 0).toString());
            gub.setSubmenupedidosvenda(tablepermissoes.getValueAt(10, 0).toString());
            gub.setSubmenuops(tablepermissoes.getValueAt(11, 0).toString());
            gub.setSubmenuprodutosvenda(tablepermissoes.getValueAt(12, 0).toString());
            gub.setMenuservicos(tablepermissoes.getValueAt(13, 0).toString());
            gub.setSubmenuorcamentosservico(tablepermissoes.getValueAt(14, 0).toString());
            gub.setSubmenupedidosservico(tablepermissoes.getValueAt(15, 0).toString());
            gub.setSubmenuoss(tablepermissoes.getValueAt(16, 0).toString());
            gub.setSubmenuprodutosservico(tablepermissoes.getValueAt(17, 0).toString());
            gub.setMenuconfiguracoes(tablepermissoes.getValueAt(18, 0).toString());
            gub.setSubmenumenus(tablepermissoes.getValueAt(19, 0).toString());
            gub.setMenucompras(tablepermissoes.getValueAt(20, 0).toString());
            gub.setSubmenusolicitacaodecompras(tablepermissoes.getValueAt(21, 0).toString());
            gub.setSubmenupedidodecompras(tablepermissoes.getValueAt(22, 0).toString());
            gub.setSubmenuinsumos(tablepermissoes.getValueAt(23, 0).toString());

            gudao.create(gub);
            txtidgrupo.setText("");
            txtnomegrupo.setText("");
            tabgrupos.setSelectedIndex(0);
            readtablegrupos();
        } else {
            GrupoDeUsuariosBean gub = new GrupoDeUsuariosBean();
            GrupoDeUsuariosDAO gudao = new GrupoDeUsuariosDAO();

            gub.setNome(txtnomegrupo.getText());
            gub.setMenuadministracao(tablepermissoes.getValueAt(0, 0).toString());
            gub.setSubmenuusuarios(tablepermissoes.getValueAt(1, 0).toString());
            gub.setSubmenugrupodeusuarios(tablepermissoes.getValueAt(2, 0).toString());
            gub.setSubmenurepresentantes(tablepermissoes.getValueAt(3, 0).toString());
            gub.setMenucomercial(tablepermissoes.getValueAt(4, 0).toString());
            gub.setSubmenuclientes(tablepermissoes.getValueAt(5, 0).toString());
            gub.setSubmenugrupodeclientes(tablepermissoes.getValueAt(6, 0).toString());
            gub.setSubmenucondicoesdepagamento(tablepermissoes.getValueAt(7, 0).toString());
            gub.setMenuvendas(tablepermissoes.getValueAt(8, 0).toString());
            gub.setSubmenuorcamentosvenda(tablepermissoes.getValueAt(9, 0).toString());
            gub.setSubmenupedidosvenda(tablepermissoes.getValueAt(10, 0).toString());
            gub.setSubmenuops(tablepermissoes.getValueAt(11, 0).toString());
            gub.setSubmenuprodutosvenda(tablepermissoes.getValueAt(12, 0).toString());
            gub.setMenuservicos(tablepermissoes.getValueAt(13, 0).toString());
            gub.setSubmenuorcamentosservico(tablepermissoes.getValueAt(14, 0).toString());
            gub.setSubmenupedidosservico(tablepermissoes.getValueAt(15, 0).toString());
            gub.setSubmenuoss(tablepermissoes.getValueAt(16, 0).toString());
            gub.setSubmenuprodutosservico(tablepermissoes.getValueAt(17, 0).toString());
            gub.setMenuconfiguracoes(tablepermissoes.getValueAt(18, 0).toString());
            gub.setSubmenumenus(tablepermissoes.getValueAt(19, 0).toString());
            gub.setMenucompras(tablepermissoes.getValueAt(20, 0).toString());
            gub.setSubmenusolicitacaodecompras(tablepermissoes.getValueAt(21, 0).toString());
            gub.setSubmenupedidodecompras(tablepermissoes.getValueAt(22, 0).toString());
            gub.setSubmenuinsumos(tablepermissoes.getValueAt(23, 0).toString());
            gub.setId(Integer.parseInt(txtidgrupo.getText()));

            gudao.update(gub);
            txtidgrupo.setText("");
            txtnomegrupo.setText("");
            tabgrupos.setSelectedIndex(0);
            readtablegrupos();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int i = tablepermissoes.getRowCount();
        for (int j = 0; j < i; j++) {
            tablepermissoes.setValueAt(false, j, 0);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int i = tablepermissoes.getRowCount();
        for (int j = 0; j < i; j++) {
            tablepermissoes.setValueAt(true, j, 0);
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton1;
    public javax.swing.JButton jButton2;
    public javax.swing.JButton jButton3;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JPanel jPanel3;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTabbedPane tabgrupos;
    public static javax.swing.JTable tablegrupos;
    public static javax.swing.JTable tablepermissoes;
    public static javax.swing.JTextField txtidgrupo;
    public static javax.swing.JTextField txtnomegrupo;
    // End of variables declaration//GEN-END:variables
}
