/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.administracao;

import Bean.UsuariosBean;
import Connection.ConnectionFactory;
import DAO.UsuariosDAO;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Marcos Filho
 */
public class Usuarios extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaCadastroUsuario
     */
    public Usuarios() {
        initComponents();
        readtableusuarios();
        readcbnivel();
    }

    public static void readtableusuarios() {
        DefaultTableModel modelo = (DefaultTableModel) tableusuarios.getModel();
        modelo.setNumRows(0);
        UsuariosDAO ud = new UsuariosDAO();

        ud.readtabelausuariosativo().forEach((c) -> {
            modelo.addRow(new Object[]{
                c.getId(),
                c.getNome(),
                c.getCargo(),
                c.getStatus()
            });
        });
    }

    public static void readcbnivel() {
        Connection con = ConnectionFactory.getConnection();

        PreparedStatement stmt = null;

        ResultSet rs = null;
        try {

            stmt = con.prepareStatement("SELECT * FROM grupo_usuarios");
            rs = stmt.executeQuery();

            while (rs.next()) {
                String nome = rs.getString("nome");
                cbnivel.addItem(nome);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Erro!" + e);
        } finally {
            ConnectionFactory.closeConnection(con, stmt, rs);
        }
    }

    public static void zeracampos() {
        txtid.setText("");
        txtnome.setText("");
        txtnome.requestFocus();
        txtapelido.setText("");
        txtcpf.setText("");
        txtrg.setText("");
        txtnascimento.setText("");
        txtemail.setText("");
        txtfixo.setText("");
        txtcelular.setText("");
        txtcargo.setText("");
        txtadmissao.setText("");
        txtdemissao.setText("");
        txtlivro.setText("");
        txtstatus.setText("");
        txtemailinterno.setText("");
        txtpis.setText("");
        txtlogin.setText("");
        txtsenha.setText("");
        checkvendedor.setSelected(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jTextField12 = new javax.swing.JTextField();
        tabusuarios = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableusuarios = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        radioativo = new javax.swing.JRadioButton();
        radioinativo = new javax.swing.JRadioButton();
        radiotodos = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        paneldadospessoais = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtnome = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtcelular = new javax.swing.JFormattedTextField();
        txtfixo = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        txtcpf = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        txtrg = new javax.swing.JFormattedTextField();
        txtnascimento = new javax.swing.JFormattedTextField();
        jLabel21 = new javax.swing.JLabel();
        txtapelido = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtcargo = new javax.swing.JTextField();
        txtemailinterno = new javax.swing.JTextField();
        txtlogin = new javax.swing.JTextField();
        txtsenha = new javax.swing.JTextField();
        txtstatus = new javax.swing.JTextField();
        txtadmissao = new javax.swing.JFormattedTextField();
        txtdemissao = new javax.swing.JFormattedTextField();
        txtpis = new javax.swing.JFormattedTextField();
        jLabel19 = new javax.swing.JLabel();
        txtlivro = new javax.swing.JFormattedTextField();
        checkvendedor = new javax.swing.JCheckBox();
        jLabel20 = new javax.swing.JLabel();
        cbnivel = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        jTextField12.setText("jTextField12");

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setTitle("Usuários");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tableusuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Cargo", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableusuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableusuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableusuarios);
        if (tableusuarios.getColumnModel().getColumnCount() > 0) {
            tableusuarios.getColumnModel().getColumn(0).setMinWidth(40);
            tableusuarios.getColumnModel().getColumn(0).setPreferredWidth(40);
            tableusuarios.getColumnModel().getColumn(0).setMaxWidth(40);
        }

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesquisa"));

        jLabel2.setText("Pesquisa");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Filtro"));

        buttonGroup1.add(radioativo);
        radioativo.setSelected(true);
        radioativo.setText("Ativo");
        radioativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioativoActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioinativo);
        radioinativo.setText("Inativo");
        radioinativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioinativoActionPerformed(evt);
            }
        });

        buttonGroup1.add(radiotodos);
        radiotodos.setText("Todos");
        radiotodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiotodosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(radioativo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioinativo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radiotodos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioativo)
                    .addComponent(radioinativo)
                    .addComponent(radiotodos))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 202, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabusuarios.addTab("Lista de Usuários", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        paneldadospessoais.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados Pessoais"));

        jLabel4.setText("Nome");

        jLabel5.setText("Data de Nascimento");

        jLabel6.setText("E-mail");

        jLabel7.setText("Telefone Fixo");

        jLabel8.setText("Telefone Celular");

        try {
            txtcelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtfixo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel9.setText("CPF");

        try {
            txtcpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel10.setText("RG");

        try {
            txtrg.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtnascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel21.setText("Como chamar:");

        javax.swing.GroupLayout paneldadospessoaisLayout = new javax.swing.GroupLayout(paneldadospessoais);
        paneldadospessoais.setLayout(paneldadospessoaisLayout);
        paneldadospessoaisLayout.setHorizontalGroup(
            paneldadospessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneldadospessoaisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneldadospessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneldadospessoaisLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtcpf, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtrg, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtapelido)
                        .addContainerGap())
                    .addGroup(paneldadospessoaisLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtnascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtemail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtfixo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtcelular, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11))))
        );
        paneldadospessoaisLayout.setVerticalGroup(
            paneldadospessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneldadospessoaisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneldadospessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtcpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(txtapelido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paneldadospessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtnascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtfixo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtcelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados na Empresa"));

        jLabel11.setText("Cargo");

        jLabel12.setText("Data de Admissão");

        jLabel13.setText("Data de Demissão");

        jLabel14.setText("Email Interno");

        jLabel15.setText("PIS");

        jLabel16.setText("Login");

        jLabel17.setText("Senha");

        jLabel18.setText("Status");

        txtstatus.setEditable(false);
        txtstatus.setBackground(new java.awt.Color(255, 255, 255));

        try {
            txtadmissao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtdemissao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtpis.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel19.setText("Livro/Folha");

        try {
            txtlivro.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtlivro.setToolTipText("");

        checkvendedor.setText("Vendedor");

        jLabel20.setText("Nível de Acesso");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtcargo, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtadmissao, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtdemissao, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtlivro, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtsenha, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(checkvendedor))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtemailinterno, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtpis, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbnivel, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(txtcargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtadmissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdemissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(txtstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(txtlivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtemailinterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(txtpis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtlogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(txtsenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkvendedor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(cbnivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setText("ID");

        txtid.setEditable(false);
        txtid.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Novo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(paneldadospessoais, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paneldadospessoais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        tabusuarios.addTab("Detalhes do Usuário", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabusuarios)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabusuarios)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radioinativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioinativoActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) tableusuarios.getModel();
        modelo.setNumRows(0);
        UsuariosDAO udao = new UsuariosDAO();

        udao.readtabelausuariosinativo().forEach((ub) -> {
            modelo.addRow(new Object[]{
                ub.getId(),
                ub.getNome(),
                ub.getCargo(),
                ub.getStatus()
            });
        });
    }//GEN-LAST:event_radioinativoActionPerformed

    private void radiotodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiotodosActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) tableusuarios.getModel();
        modelo.setNumRows(0);
        UsuariosDAO udao = new UsuariosDAO();

        udao.readtabelausuariostodos().forEach((ub) -> {
            modelo.addRow(new Object[]{
                ub.getId(),
                ub.getNome(),
                ub.getCargo(),
                ub.getStatus()
            });
        });
    }//GEN-LAST:event_radiotodosActionPerformed

    private void radioativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioativoActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) tableusuarios.getModel();
        modelo.setNumRows(0);
        UsuariosDAO udao = new UsuariosDAO();

        udao.readtabelausuariosativo().forEach((ub) -> {
            modelo.addRow(new Object[]{
                ub.getId(),
                ub.getNome(),
                ub.getCargo(),
                ub.getStatus()
            });
        });
    }//GEN-LAST:event_radioativoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int i = JOptionPane.showConfirmDialog(rootPane, "Deseja cadastrar um novo usuário?", "Novo Usuário", JOptionPane.YES_NO_OPTION);
        if (i == 0) {
            zeracampos();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String dem = txtdemissao.getText();
        if (txtnome.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Coloque um nome!");
        } else if (txtlogin.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Coloque um Login!");
        } else if (txtsenha.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Coloque uma senha!");
        } else if (txtid.getText().equals("")) {
            UsuariosBean ub = new UsuariosBean();
            UsuariosDAO udao = new UsuariosDAO();

            String vend;

            ub.setNome(txtnome.getText());
            ub.setCpf(txtcpf.getText());
            ub.setRg(txtrg.getText());
            ub.setApelido(txtapelido.getText());
            ub.setDatanascimento(txtnascimento.getText());
            ub.setEmailpessoal(txtemail.getText());
            ub.setTelefonefixo(txtfixo.getText());
            ub.setTelefonecelular(txtcelular.getText());
            ub.setCargo(txtcargo.getText());
            ub.setDataadmissao(txtadmissao.getText());
            ub.setDatademissao(txtdemissao.getText());
            ub.setLivrofolha(txtlivro.getText());
            ub.setStatus("Ativo");
            ub.setEmailfabrica(txtemailinterno.getText());
            ub.setPis(txtpis.getText());
            ub.setLogin(txtlogin.getText());
            ub.setSenha(txtsenha.getText());
            if (checkvendedor.isSelected()) {
                vend = "true";
            } else {
                vend = "false";
            }
            ub.setVendedor(vend);
            ub.setNivel(cbnivel.getSelectedItem().toString());
            udao.create(ub);
            zeracampos();
            tabusuarios.setSelectedIndex(0);
            readtableusuarios();
        } else if (txtdemissao.getText().equals(dem)) {
            UsuariosBean cbean = new UsuariosBean();
            UsuariosDAO cdao = new UsuariosDAO();

            String vend;

            cbean.setNome(txtnome.getText());
            cbean.setApelido(txtapelido.getText());
            cbean.setEmailpessoal(txtemail.getText());
            cbean.setDataadmissao(txtadmissao.getText());
            cbean.setTelefonefixo(txtfixo.getText());
            cbean.setTelefonecelular(txtcelular.getText());
            cbean.setDatanascimento(txtnascimento.getText());
            cbean.setDatademissao(txtdemissao.getText());
            cbean.setEmailfabrica(txtemailinterno.getText());
            if (checkvendedor.isSelected()) {
                vend = "true";
            } else {
                vend = "false";
            }
            cbean.setVendedor(vend);
            cbean.setLogin(txtlogin.getText());
            cbean.setSenha(txtsenha.getText());
            cbean.setCargo(txtcargo.getText());
            cbean.setCpf(txtcpf.getText());
            cbean.setPis(txtpis.getText());
            cbean.setRg(txtrg.getText());
            cbean.setLivrofolha(txtlivro.getText());
            cbean.setStatus("Ativo");
            cbean.setNivel(cbnivel.getSelectedItem().toString());
            cbean.setId(Integer.parseInt(txtid.getText()));
            cdao.update(cbean);
            zeracampos();
            tabusuarios.setSelectedIndex(0);
            readtableusuarios();
        } else {
            UsuariosBean cbean = new UsuariosBean();
            UsuariosDAO cdao = new UsuariosDAO();

            String vend;

            cbean.setNome(txtnome.getText());
            cbean.setEmailpessoal(txtemail.getText());
            cbean.setDataadmissao(txtadmissao.getText());
            cbean.setTelefonefixo(txtfixo.getText());
            cbean.setTelefonecelular(txtcelular.getText());
            cbean.setDatanascimento(txtnascimento.getText());
            cbean.setDatademissao(txtdemissao.getText());
            cbean.setEmailfabrica(txtemailinterno.getText());
            if (checkvendedor.isSelected()) {
                vend = "true";
            } else {
                vend = "false";
            }
            cbean.setVendedor(vend);
            cbean.setStatus("Inativo");
            cbean.setLogin(txtlogin.getText());
            cbean.setSenha(txtsenha.getText());
            cbean.setCargo(txtcargo.getText());
            cbean.setCpf(txtcpf.getText());
            cbean.setPis(txtpis.getText());
            cbean.setRg(txtrg.getText());
            cbean.setLivrofolha(txtlivro.getText());
            cbean.setNivel(cbnivel.getSelectedItem().toString());
            cbean.setApelido(txtapelido.getText());
            cbean.setId(Integer.parseInt(txtid.getText()));
            
            //nome = ?, emailpessoal = ?, dataadmissao = ?, telefonefixo = ?, telefonecelular = ?, datanascimento = ?, datademissao = ?, emailfabrica = ?, vendedor = ?, status = ?, login = ?, senha = ?, cargo = ?, cpf = ?, pis = ?, rg = ?, livrofolha = ?, nivel = ? , apelido = ? WHERE id = ?
            cdao.update(cbean);
            zeracampos();
            tabusuarios.setSelectedIndex(0);
            readtableusuarios();
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void tableusuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableusuariosMouseClicked
        if (evt.getClickCount() == 2) {
            tabusuarios.setSelectedIndex(1);
            txtid.setText(tableusuarios.getValueAt(tableusuarios.getSelectedRow(), 0).toString());
            UsuariosDAO udao = new UsuariosDAO();

            udao.readusuarioclick().forEach((ub) -> {
                txtnome.setText(ub.getNome());
                txtcpf.setText(ub.getCpf());
                txtrg.setText(ub.getRg());
                txtapelido.setText(ub.getApelido());
                txtnascimento.setText(ub.getDatanascimento());
                txtemail.setText(ub.getEmailpessoal());
                txtfixo.setText(ub.getTelefonefixo());
                txtcelular.setText(ub.getTelefonecelular());
                txtcargo.setText(ub.getCargo());
                txtadmissao.setText(ub.getDataadmissao());
                txtdemissao.setText(ub.getDatademissao());
                txtlivro.setText(ub.getLivrofolha());
                txtstatus.setText(ub.getStatus());
                txtemailinterno.setText(ub.getEmailfabrica());
                txtpis.setText(ub.getPis());
                txtlogin.setText(ub.getLogin());
                txtsenha.setText(ub.getSenha());
                String vend = ub.getVendedor();
                if (vend.equals("true")) {
                    checkvendedor.setSelected(true);
                } else {
                    checkvendedor.setSelected(false);
                }
                cbnivel.setSelectedItem(ub.getNivel());
            });
        }
    }//GEN-LAST:event_tableusuariosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    public static javax.swing.JComboBox<String> cbnivel;
    public static javax.swing.JCheckBox checkvendedor;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField12;
    public static javax.swing.JPanel paneldadospessoais;
    public static javax.swing.JRadioButton radioativo;
    public static javax.swing.JRadioButton radioinativo;
    public static javax.swing.JRadioButton radiotodos;
    public static javax.swing.JTable tableusuarios;
    private javax.swing.JTabbedPane tabusuarios;
    public static javax.swing.JFormattedTextField txtadmissao;
    public static javax.swing.JTextField txtapelido;
    public static javax.swing.JTextField txtcargo;
    public static javax.swing.JFormattedTextField txtcelular;
    public static javax.swing.JFormattedTextField txtcpf;
    public static javax.swing.JFormattedTextField txtdemissao;
    public static javax.swing.JTextField txtemail;
    public static javax.swing.JTextField txtemailinterno;
    public static javax.swing.JFormattedTextField txtfixo;
    public static javax.swing.JTextField txtid;
    public static javax.swing.JFormattedTextField txtlivro;
    public static javax.swing.JTextField txtlogin;
    public static javax.swing.JFormattedTextField txtnascimento;
    public static javax.swing.JTextField txtnome;
    public static javax.swing.JFormattedTextField txtpis;
    public static javax.swing.JFormattedTextField txtrg;
    public static javax.swing.JTextField txtsenha;
    public static javax.swing.JTextField txtstatus;
    // End of variables declaration//GEN-END:variables
}
